src/com/maddyhome/idea/vim/regexp/CharPointer.java
test/org/jetbrains/plugins/ideavim/group/SearchGroupTest.java

Fixes https://youtrack.jetbrains.com/issue/VIM-855
Previously strchr and istrchr didn't consider NUL chars as end-of-string
terminators. This caused problems in regexps using character classes:
a regexp like "[^a]bc" would be effectively treated as "[^abc]bc" - i.e.
some literal characters from the rest of the pattern would accidentally be
included in the character class.

VIM-855 Fix regexp character class bugs

---

src/com/maddyhome/idea/vim/ex/ExOutputModel.java
src/com/maddyhome/idea/vim/group/MotionGroup.java
src/com/maddyhome/idea/vim/group/ProcessGroup.java
src/com/maddyhome/idea/vim/ui/ExEntryPanel.java
src/com/maddyhome/idea/vim/ui/ExOutputPanel.java
test/org/jetbrains/plugins/ideavim/VimTestCase.java

Fixes https://youtrack.jetbrains.com/issue/VIM-210 and also https://youtrack.jetbrains.com/issue/VIM-178 which is a duplicate of VIM-210.
Previously, if the editor window had been splitted, under certain
conditions some actions related to the Ex panel would cause the editor
focus to change to a different split.
The required conditions for this bug to occur:
- no docked windows (like the Project sidebar) are open
- 'View -> Navigation bar' is disabled
At least these actions triggered the bug:
- search with /
- successfully executing an Ex command
- dismissing the Ex window with Esc
- Ex commands that opened the output panel (e.g. :!)
All the deleted lines of the form
FileEditorManager.getInstance(project).openFile(vf, true);
seem to be very old, non-functional workarounds for the focus …

VIM-210 Fix focus issues with the Ex panel

---

src/com/maddyhome/idea/vim/group/MotionGroup.java

Fixes https://youtrack.jetbrains.com/issue/VIM-575
If a file is opened in multiple splits, entering visual mode in one
split would change the cursor position in other splits as well.

VIM-575 Don't change cursor position of other splits in visual mode

---

src/com/maddyhome/idea/vim/group/SearchGroup.java
test/org/jetbrains/plugins/ideavim/ex/SubstituteCommandTest.java

Fixes https://youtrack.jetbrains.com/issue/VIM-864
Previously, running a substitute command in visual mode would
incorrectly set the visual mode end mark (>) to the location of the last
search match.

VIM-864 Fix visual marks gettinng changed during visual substitute

---

src/com/maddyhome/idea/vim/group/ChangeGroup.java
test/org/jetbrains/plugins/ideavim/ex/SortCommandTest.java

`StringUtil.splitByLines` incorrectly splits strings with leading whitespace. For example, ` a\n b\n c\n` is split into `[ a,b,c]` instead of `[ a, b, c]`.
This meant that if an IdeaVim user tried to sort lines with leading whitespace, the sorting was incorrect.
I changed the implementation from `StringUtil.splitByLines` to Guava's `Splitter` and added a unit test.

Fix broken sorting when sorting with leading whitespace

---

src/com/maddyhome/idea/vim/ex/CommandParser.java
test/org/jetbrains/plugins/ideavim/ex/SubstituteCommandTest.java

Substitution commands with offset ranges like .,+2s/a/b/g previously
did not work the way they do in Vim (replace a with b on the current
line and the next two lines). This change fixes that bug.

Fix incorrect behavior in substitution with offset ranges

---

src/com/maddyhome/idea/vim/regexp/RegExp.java
test/org/jetbrains/plugins/ideavim/group/SearchGroupTest.java

Fixes https://youtrack.jetbrains.com/issue/VIM-856
The regex code has the following bugs, mostly related to lookbehind:
- Comparison of CharPointers with == is wrong, .equals should be
used instead.
- In the original C code, the behind_pos variable is declared as
'static regsave_T behind_pos;', i.e. not a pointer, and the same
for other variables of type regsave_T. So assignments to these
types of variables need to make deep copies.

VIM-856 Fix regex lookbehind bugs

---

src/com/maddyhome/idea/vim/helper/PsiHelper.java

The zero-parameter overload of createStructureViewModel() has been
marked deprecated and is now removed.

Make IdeaVIM build on latest intellij-community master

---

src/com/maddyhome/idea/vim/KeyHandler.java
test/org/jetbrains/plugins/ideavim/ex/MapCommandTest.java

Fixes https://youtrack.jetbrains.com/issue/VIM-700
Previously, remapping '0' in command mode would prevent a number zero
from being entered in a command count.

VIM-700 Remapping '0' should still allow zero to be entered in count

---

src/com/maddyhome/idea/vim/group/MotionGroup.java
src/com/maddyhome/idea/vim/helper/EditorData.java
test/org/jetbrains/plugins/ideavim/action/ChangeActionTest.java
test/org/jetbrains/plugins/ideavim/action/MotionActionTest.java

Fixes https://youtrack.jetbrains.com/issue/VIM-781 and https://youtrack.jetbrains.com/issue/VIM-845
The current visual block mode implementation has several bugs:
- The GUI never displays the rightmost characters as selected (blue)
- Due to some off-by-one, commands can't act on each line's last character
- It's possible for newlines to get deleted/changed into something else
- If the '$' mode is entered, the GUI doesn't always indicate this
- It's impossible to move to an empty line (VIM-781)
This commit fixes all of those problems. The only remaining problem are
the visible secondary carets, which makes seeing the real cursor a bit
difficult. This could be fixed later if support for per-caret visibility
would be added to IntelliJ core.

Visual block mode overhaul

---

README.md

This example may be helpful to regular VIM users since the :action and
:actionlist commands are specific to IdeaVIM.

Change - add mapping example using :action

---

src/com/maddyhome/idea/vim/VimPlugin.java
src/com/maddyhome/idea/vim/ex/CommandParser.java
src/com/maddyhome/idea/vim/ex/handler/EchoHandler.java
src/com/maddyhome/idea/vim/ex/handler/LetHandler.java
src/com/maddyhome/idea/vim/ex/handler/MapHandler.java
src/com/maddyhome/idea/vim/ex/handler/SetHandler.java
src/com/maddyhome/idea/vim/ex/handler/SourceHandler.java
src/com/maddyhome/idea/vim/ex/vimscript/VimScriptCommandHandler.java
src/com/maddyhome/idea/vim/ex/vimscript/VimScriptGlobalEnvironment.java
src/com/maddyhome/idea/vim/ex/vimscript/VimScriptParser.java
src/com/maddyhome/idea/vim/helper/StringHelper.java
test/org/jetbrains/plugins/ideavim/ex/MapCommandTest.java
test/org/jetbrains/plugins/ideavim/ex/VimScriptParserTest.java

Currently only very simple `let` and `echo` commands are supported. Using the `mapleader` value in mappings is coming next.

Mapleader support based on the prototype of a Vim script expressions evaluator

---

src/com/maddyhome/idea/vim/helper/PsiHelper.java
src/com/maddyhome/idea/vim/helper/SearchHelper.java
test/org/jetbrains/plugins/ideavim/VimTestCase.java
test/org/jetbrains/plugins/ideavim/action/MotionActionTest.java

In Vim, `%` can be used to jump between the `/*` and `*/` of block
comments. Support this functionality in a language-independent manner.

Support comments in brace matching

---

README.md

Hi, I changed the link to the relative link. Because this one is simple and is useful for a forked developer.
See also: [Relative links in READMEs - User Documentation](https://help.github.com/articles/relative-links-in-readmes/ "Relative links in READMEs - User Documentation")

Use relative links that recommended way by GitHub Inc.

---

resources/META-INF/plugin.xml
resources/messages.properties
src/com/maddyhome/idea/vim/KeyHandler.java
src/com/maddyhome/idea/vim/action/change/OperatorAction.java
src/com/maddyhome/idea/vim/ex/handler/MapHandler.java
src/com/maddyhome/idea/vim/extension/VimExtension.java
src/com/maddyhome/idea/vim/extension/VimExtensionFacade.java
src/com/maddyhome/idea/vim/extension/VimExtensionHandler.java
src/com/maddyhome/idea/vim/extension/VimNonDisposableExtension.java
src/com/maddyhome/idea/vim/extension/surround/VimSurroundExtension.java
src/com/maddyhome/idea/vim/group/ChangeGroup.java
src/com/maddyhome/idea/vim/group/CopyGroup.java
src/com/maddyhome/idea/vim/group/KeyGroup.java
src/com/maddyhome/idea/vim/group/MarkGroup.java
src/com/maddyhome/idea/vim/group/RegisterGroup.java
src/com/maddyhome/idea/vim/helper/EditorData.java
src/com/maddyhome/idea/vim/helper/StringHelper.java
src/com/maddyhome/idea/vim/helper/TestInputModel.java
src/com/maddyhome/idea/vim/key/KeyMapping.java
src/com/maddyhome/idea/vim/key/MappingInfo.java
src/com/maddyhome/idea/vim/key/OperatorFunction.java
src/com/maddyhome/idea/vim/option/Options.java
src/com/maddyhome/idea/vim/package-info.java
src/com/maddyhome/idea/vim/ui/ModalEntryDialog.java
test/org/jetbrains/plugins/ideavim/VimTestCase.java
test/org/jetbrains/plugins/ideavim/extension/surround/VimSurroundExtensionTest.java

I've added the following:
1. An extension point `IdeaVIM.vimExtension`. for registering IdeaVim extensions. See plugin.xml and `VimSurroundExtension` as an example. You have to add a `<vimExtension/>` tag into plugin.xml and inherit from `VimExtension` in order to get your plugin registered and get the `set <plguin-name>` option working.
2. The `VimExtensionFacade` contains the parts of the API for extension authors that is similar to Vim.
3. Extension actions are registered via `putExtensionHandlerMapping()` similar to `:map ... :call <your-extension-handler>` in Vim.
4. If your extension handler requires an argument, use `operatorfunc` (available as `setOperatorFunction()`) and `g@` as in Vim.
5. `getchar()` is implemented as a modal dialog that looks like Vim input line at the bottom …

Framework for IdeaVim extensions + sketch of vim-surround port

---

src/com/maddyhome/idea/vim/group/RegisterGroup.java
test/org/jetbrains/plugins/ideavim/action/SpecialRegistersTest.java

The original behavior slightly differs from VIM. This caused the root problem of [VIM-581](https://youtrack.jetbrains.com/issue/VIM-581) (it turned out that it's not a macro problem).
Changes:
* Only multiline deletes (a line or more) go to registers "1"-"9", unless a register is specified or it's a special case (details can be found in VIM docs, registers topic).
* Small deletes (less than a line) go to the register "-" only if no registers were specified.
* Added tests to cover numbered registers (including "0") and "-" logic.

More correct numbered registers behavior (fixes VIM-581)

---

src/com/maddyhome/idea/vim/group/MarkGroup.java
test/org/jetbrains/plugins/ideavim/action/MarkTest.java

This PR contains:
1. Fix for VIM-964. A mark got deleted if a whole content of a line (with that mark) is changed.
2. If a change was made (starting from the beginning of a line till some point on next lines), then marks on the first line were removed. Actually VIM doesn't remove such marks, because technically the first line still exists (even if subsequent lines got removed). So the second commit fixes this.
3. Marks were moved up incorrectly if you remove several lines before them in a text without leading spaces (without indentation). The third commit fixes that.
4. Tests for all these problems.

Fix for VIM-964 along with other marks improvements

---

resources/META-INF/plugin.xml
src/com/maddyhome/idea/vim/RegisterActions.java
src/com/maddyhome/idea/vim/action/change/change/AutoIndentLinesVisualAction.java
src/com/maddyhome/idea/vim/action/change/shift/AutoIndentMotionAction.java
src/com/maddyhome/idea/vim/group/ChangeGroup.java
src/com/maddyhome/idea/vim/group/CopyGroup.java
test/org/jetbrains/plugins/ideavim/action/AutoIndentTest.java

This PR fixes VIM-259, allows using counts for == and adds ={motion} action.

={motion} implementation, == with count and fix for VIM-259

---

src/com/maddyhome/idea/vim/RegisterActions.java

Hi!
I love the folding methods and I was in need of zC and zO (specially zO). So I saw that it was very straightforward to add them and went ahead and do it. I tested this on a dev environment. Please let me know your thoughts.
Cheers!

Adds zC and zO folding commands

---

src/com/maddyhome/idea/vim/action/change/RepeatChangeAction.java
src/com/maddyhome/idea/vim/group/MotionGroup.java
test/org/jetbrains/plugins/ideavim/action/ChangeActionTest.java

On the original vim when we repeat a change with . that also contain an find movement the last find that was typed before the repeat is the one used by the motion repeat ;. Before the commit the plugin would have reset the last movement to use the movement contained in the command that was repeated.
To solve this I took a simple approach where I save the last find motion before starting the repeat and then restoring it to its original value after the repeat is over. In order to access the find motion fields from RepeatChangeAction I created getters in MotionGroup for the movement type and character.
modified:   src/com/maddyhome/idea/vim/action/change/RepeatChangeAction.java
modified:   src/com/maddyhome/idea/vim/group/MotionGroup.java
modified: …

Fixed . reseting the last find movement 

---

src/com/maddyhome/idea/vim/ex/handler/ActionHandler.java
test/org/jetbrains/plugins/ideavim/ex/VariousCommandsTest.java

Fixes the following issue VIM-862 ":action ExtractMethod doesn't work in visual mode".
https://youtrack.jetbrains.com/issue/VIM-862
Not only `:action ExtractMethod` works but also generic :action commands do. 
(e.g. `CommandByLineComment`, `CommandByBlockComment`, `ReformatCode`, ...)

VIM-862 Make :action commands work in visual mode

---

src/com/maddyhome/idea/vim/group/ChangeGroup.java
test/org/jetbrains/plugins/ideavim/action/ChangeActionTest.java

`TextRange.size()` should be used only for iterating over starts/ends.
I am not sure that this is a proper fix. However it seems consistent with current implementation and passes all tests.

VIM-1379 Changing visual block correctly handles short lines

---

src/com/maddyhome/idea/vim/helper/SearchHelper.java
test/org/jetbrains/plugins/ideavim/action/MotionActionTest.java

Add support for commands like "yi(" or "di{" when caret and braces are inside the string

Fix vim 1287

---

src/com/maddyhome/idea/vim/helper/StringHelper.java
test/org/jetbrains/plugins/ideavim/group/SearchGroupTest.java

StringHelper.containsUpperCase should return true when one of
the character of the input string satisfies the following two
conditions:
1. The character is upper case.
2. The character is not prefixed with a backslash.
Before this fix, the second condition was incorrectly written.

VIM-1274 Fix StringHelper.containsUpperCase behavior

---

src/com/maddyhome/idea/vim/action/window/WindowDownAction.java
src/com/maddyhome/idea/vim/action/window/WindowLeftAction.java
src/com/maddyhome/idea/vim/action/window/WindowRightAction.java
src/com/maddyhome/idea/vim/action/window/WindowUpAction.java

Add new mappings to allow window navigation with arrow keys:
- ^W-left as ^W-h
- ^W-down as ^W-j
- ^W-up as ^W-k
- ^W-right as ^W-l
`package-info.java` already contains links to actions and doesn't require editing.

VIM-798 Arrow keys for window navigation commands

---

gradle.properties
src/com/maddyhome/idea/vim/helper/EditorHelper.java

Fixes [VIM-1187](https://youtrack.jetbrains.com/issue/VIM-1187), which is a performance issue with large files and the `relativenumber` option. The fix uses the alternative API as specified in [this comment](https://youtrack.jetbrains.com/issue/VIM-1187#focus=streamItem-27-3057288-0-0). However, this also means bumping required IJ version to 2018.3.

VIM-1187: Fix performance issue with relative line numbers + large files

---

gradle.properties
resources/META-INF/plugin.xml
src/com/maddyhome/idea/vim/action/internal/AddInlaysAction.java
src/com/maddyhome/idea/vim/action/motion/screen/MotionLastScreenLineAction.java
src/com/maddyhome/idea/vim/action/motion/scroll/MotionScrollFirstScreenLineAction.java
src/com/maddyhome/idea/vim/action/motion/scroll/MotionScrollFirstScreenLinePageStartAction.java
src/com/maddyhome/idea/vim/action/motion/scroll/MotionScrollFirstScreenLineStartAction.java
src/com/maddyhome/idea/vim/action/motion/scroll/MotionScrollHalfPageDownAction.java
src/com/maddyhome/idea/vim/action/motion/scroll/MotionScrollHalfPageUpAction.java
src/com/maddyhome/idea/vim/action/motion/scroll/MotionScrollLastScreenLineAction.java
src/com/maddyhome/idea/vim/action/motion/scroll/MotionScrollLastScreenLinePageStartAction.java
src/com/maddyhome/idea/vim/action/motion/scroll/MotionScrollLastScreenLineStartAction.java
src/com/maddyhome/idea/vim/action/motion/scroll/MotionScrollMiddleScreenLineAction.java
src/com/maddyhome/idea/vim/action/motion/scroll/MotionScrollMiddleScreenLineStartAction.java
src/com/maddyhome/idea/vim/group/MotionGroup.java
src/com/maddyhome/idea/vim/helper/EditorHelper.java

This PR changes the way scrolling and motion work to take intra-line block inlays, such as Rider's Code Vision. It changes the implementation from being fundamentally line based to being more based on scroll offsets, since the inlays mean that the height of the screen is not constant. When inlays are not displayed, it behaves as though it were still line based.
When inlays are displayed, there are some changes in behaviour:
* Scrolling and motion commands mostly try to keep the top line aligned with the top of the screen. When the top line has inlays attached above it, the line is moved so that the inlay is visible.
* When scrolling down, the bottom line's trailing inlays are always visible, and the top line (with leading inlays) is also kept aligned.
* `M` does not follow this behaviour …

VIM-1558 Support block inlays in scrolling and motion

---

src/com/maddyhome/idea/vim/group/SearchGroup.java
test/org/jetbrains/plugins/ideavim/group/SearchGroupTest.java

fixes https://youtrack.jetbrains.com/issue/VIM-1119
makes `/two/e-1` work and the other implemented offsets
whats not working:
* search highlight  - once you are at the second `/` highlight stops
* `N` - `SearchAgainPreviousAction`
if you have pointers how to make that work, I'll give it a shot

make offset work in normal search

---

AUTHORS.md

John Grib's email address recorded as johngrib@woowahan.com
is currently not valid.
I am currently using johngrib82@gmail.com.
You can see my merged PR and my recent email address
through the following two links.
* https://github.com/JetBrains/ideavim/pull/115
* https://github.com/johngrib

Fix the wrong email address

---

src/com/maddyhome/idea/vim/helper/SearchHelper.java
test/org/jetbrains/plugins/ideavim/action/MotionActionTest.java

**Problem**
When in visual mode, the caret is allowed to go one past the end of the line, which is consistent with the behaviour in the real Vim editor. However, in this state, ideavim doesn't correctly respond to the *%* action to find a matching parenthesis or brace.  This issue comes up a lot when you use a language that typically has an open curly brace at the end of the line.
**Current Behaviour**
Pressing *v$%* to enter visual mode, go to the end of line, and then find the matching brace, should select the whole function in the example below. But since the caret is one character past the end of the line, ideavim doesn't recognize the newline as a pairable character, and nothing happens.
If you want to use *%* to find the matching curly brace, you currently must first press *h* to go …

Support end-of-line multi line percent match in visual mode

---

src/com/maddyhome/idea/vim/extension/surround/VimSurroundExtension.java
test/org/jetbrains/plugins/ideavim/extension/surround/VimSurroundExtensionTest.java

Fixes [VIM-1569](https://youtrack.jetbrains.com/issue/VIM-1569) - Surrounding visually selected text adds class attribute to end tag
There appears to be an additional issue - that the selected text is not surrounded by line breaks in Visual-Line mode.

VIM-1569: Strip tag attributes from closing tag for Vim-Surround

---

resources/META-INF/plugin.xml
src/com/maddyhome/idea/vim/KeyHandler.java
src/com/maddyhome/idea/vim/extension/commentary/CommentaryExtension.java
test/org/jetbrains/plugins/ideavim/JavaVimTestCase.java
test/org/jetbrains/plugins/ideavim/ex/MapCommandTest.java
test/org/jetbrains/plugins/ideavim/extension/commentary/CommentaryExtensionTest.java

@vlasovskikh Thanks for your work on #105. Here's another try at an extension for providing motion-based comment actions, based off the latest master. This PR will initially serve as more discussion, however, as trying to use the `<Plug>` support is causing some issues that I haven't had time to fully investigate. Basically, the PR mostly works as-is, but without `<Plug>` maps.  When I uncomment the `<Plug>` maps, it seems to want an extra operator before performing the action. 
More concretely, when using the `<Plug>` map indirection: 
- `gcc` works as expected, but it seems to also add an extra `c` as input, such that then hitting `j` will delete the current and next lines and enter insert mode)
- `gcl` to do a block comment around one letter will appear to only accept the `l` to move …

Another attempt at comment motion extension

---

src/com/maddyhome/idea/vim/helper/SearchHelper.java
test/org/jetbrains/plugins/ideavim/helper/SearchHelperTest.java

In insert mode, "a(" to
`((int) nu<caret>m)`
should cover the whole block, but it covers only `(int)`.
I fixed the bug.

Fix findBlockRange

---

src/com/maddyhome/idea/vim/group/ChangeGroup.java
test/org/jetbrains/plugins/ideavim/action/ChangeActionTest.java

The variable `ChangeGroup.oldOffset` should be initialized before every insertion action.
This fixes https://youtrack.jetbrains.com/issue/VIM-1067

 Fix issue VIM-1067: Repeat commands deletes End Of Line character when repeating "append to end of line" ('A') command.

---

src/com/maddyhome/idea/vim/group/MotionGroup.java
src/com/maddyhome/idea/vim/helper/EditorHelper.java

This PR will fix handling of `scrolloff` being larger than half the height of the screen, and will keep the current line centred in the screen.

VIM-1615 Fix handling of so=999

---

src/com/maddyhome/idea/vim/ex/CommandParser.java
src/com/maddyhome/idea/vim/ex/handler/TabOnlyHandler.kt
src/com/maddyhome/idea/vim/group/WindowGroup.java
test/org/jetbrains/plugins/ideavim/ex/handler/TabOnlyHandlerTest.kt

Implement `:tabonly` command as described in [vim tab tips page](https://vim.fandom.com/wiki/Using_tab_pages).
_____
My congrats to maintainers, I found this repo very tidy and code very easy to browse and understand. :clap: 
This pull request has been developed during [Open Source Saturday #23](https://www.meetup.com/it-IT/Open-Source-Saturday-Milano/events/259527969/) meetup in Milan.

Implement TabOnlyHandler

---

.editorconfig
src/com/maddyhome/idea/vim/common/IndentConfig.java
src/com/maddyhome/idea/vim/group/ChangeGroup.java
src/com/maddyhome/idea/vim/helper/EditorHelper.java

Fixes https://youtrack.jetbrains.net/issue/VIM-1231
I wasn't sure what the difference was between `PlatformDataKeys.PROJECT.getData(context)` and `editor.getProject()`, so I opted to leave the current behavior (former) where `context` was available.

Get indent from PsiFile so formatting on shift is consistent (VIM-1231)

---

src/com/maddyhome/idea/vim/ex/handler/ActionListHandler.kt
test/org/jetbrains/plugins/ideavim/ex/ActionListCommandTest.java

So far, we can search an action by `:actionlist PartOfSomeActionName` command but there is no way to know action name of IntelliJ functions which we want to use as IdeaVim action.
So I think it is useful to search an action by keyboard shortcuts which is assigned to the action.
When execute `:actionlist <M-I>`, the result is following.
```
--- Actions ---
ImplementMethods                                   <M-I>
MethodHierarchy.ImplementMethodAction              <M-I>
```
When execute `:actionlist <M-S-`, the result is following.
```
--- Actions ---
$Redo                                              <M-S-Z> <A-S-BS>
ActivateVersionControlToolWindow                   <M-9> <M-S-9>
ChangeTypeSignature                                <M-S-F6>
CloseActiveTab …
```

Search actionlist by keyboard shortcuts which is assigned to action

---

src/com/maddyhome/idea/vim/VimPlugin.java
src/com/maddyhome/idea/vim/common/Alias.kt
src/com/maddyhome/idea/vim/ex/CommandParser.java
src/com/maddyhome/idea/vim/ex/handler/CmdClearHandler.kt
src/com/maddyhome/idea/vim/ex/handler/CmdHandler.kt
src/com/maddyhome/idea/vim/ex/handler/DelCmdHandler.kt
src/com/maddyhome/idea/vim/group/CommandGroup.kt
src/com/maddyhome/idea/vim/package-info.java
test/org/jetbrains/plugins/ideavim/ex/handler/CmdClearHandlerTest.kt
test/org/jetbrains/plugins/ideavim/ex/handler/CmdHandlerTest.kt
test/org/jetbrains/plugins/ideavim/ex/handler/DelCmdHandlerTest.kt

Commands `command`, `comclear` and `delcommand` have been added. `command` also
supports -nargs, allowing arguments to be passed to the aliased command.
Symbols supported for -nargs are: `<args> <q-args> <count> <lt>`.
For example:
```vim
command WQ wq
```
Will allow `WQ` to be used as an alias for `wq`.
Documentation: http://vimdoc.sourceforge.net/htmldoc/map.html#:command
Please give me some feedback. 
Fixes [VIM-1105](https://youtrack.jetbrains.com/issue/VIM-1105)
Example:
@AlexPl292 This was just easier than trying to fix my fork that I broke when I tried to rebase.

(VIM-1105) Adding support for command aliasing.

---

src/com/maddyhome/idea/vim/VimPlugin.java

Simple change to only play the system beep once every half second, the same as Vim (see [:help 'visualbell'](https://vimhelp.org/options.txt.html#%27visualbell%27)).

Only beep once every half second

---

src/com/maddyhome/idea/vim/RegisterActions.java
src/com/maddyhome/idea/vim/group/KeyGroup.java

Ensures that the keyboard shortcuts required for digraphs (`<C-K>`, `<C-V>`, `<C-Q>` and `<BS>`) are all explicitly registered. 
Digraphs are handled directly by the key handler, so there is no action that can provide keys to be registered. If the keys aren't registered, the key stroke doesn't get to the key handler and digraphs don't work. 
Technically, these shortcuts are already registered by other actions, but it is better to be explicit, as [VIM-1061](https://youtrack.jetbrains.com/issue/VIM-1061) demonstrates. Digraphs with `<C-K>` were broken in 0.51, but fixed by accident by #194, which included the key sequence `<C-W><C-K>`, meaning `<C-K>` is registered.
Tests are not possible for this change as it affects the IDE event loop and the tests invoke `handleKey` directly,

VIM-1061 Explicitly register shortcuts for digraphs

---

src/com/maddyhome/idea/vim/group/RegisterGroup.java

While compiling [test cases](https://gist.github.com/thecodewarrior/7d766a97c377090470497c8af8e29527) for [VIM-1473](https://youtrack.jetbrains.com/issue/VIM-1473) I discovered that the unnamed registers (aka system clipboard) weren't retaining the selection type when yanked into and were making untrue assumptions as to what text copied in visual block mode would look like. 
In this PR I add a condition so the unnamed registers won't be overwritten unless the clipboard changes (thus they will retain the selection mode IDEAVim initially assigned them until someone copies different text) and removed visual block selections from guess function, as I can't think of any situation in which one would copy text outside of IDEA and want to paste it as if it were copied in visual block selection …

VIM-1473 Fixed incorrect selection type for unnamed registers

---

doc/set-commands.md
src/com/maddyhome/idea/vim/group/NotificationService.kt

Recent commit d06f2a2d181e46c7737c2919fff9d7171d444f3b moved ideajoin examples page from doc/ to wiki.

Fix ideajoin examples URL

---

resources/META-INF/plugin.xml
src/com/maddyhome/idea/vim/group/EditorGroup.java
src/com/maddyhome/idea/vim/helper/EditorHelper.java
src/com/maddyhome/idea/vim/helper/UserDataManager.kt

This PR makes relative line numbers play (mostly) nice with VCS annotations. The current implementation is a `TextAnnotationGutterProvider`, which is a core platform API, but only really implemented by the VCS subsystem. 
The main problem today (notably [VIM-1032](https://youtrack.jetbrains.com/issue/VIM-1032)) is that the VCS subsystem doesn't expect other annotation providers, and incorrectly shows annotations as enabled when they're not. Toggling (twice) will show the VCS annotations, but moving the caret closes them and shows the relative line numbers again.
There isn't a solution that perfectly fixes everything, but this PR gives the best implementation, by firstly improving the presentation and behaviour of the gutter provider and secondly replacing it with a line number converter …

Improve relative line numbers and VCS annotations

---

resources/messages.properties
src/com/maddyhome/idea/vim/ex/CommandParser.java
src/com/maddyhome/idea/vim/ex/handler/DeleteMarksHandler.kt
src/com/maddyhome/idea/vim/group/MarkGroup.java
src/com/maddyhome/idea/vim/helper/Msg.java
test/org/jetbrains/plugins/ideavim/ex/handler/DeleteMarksHandlerTest.kt

Deletes existing marks. See
http://vimdoc.sourceforge.net/htmldoc/motion.html#:delmarks
for details.
[VIM-1720](https://youtrack.jetbrains.com/issue/VIM-1720)
Note that the `'` jump mark cannot be deleted with this command. This is why I decided to define the deletable marks separately from the constants already defined in `MarkGroup`, but I'd like some feedback on whether this is a good idea or not.
Similarly I've preprocessed the argument to account for all edge cases I could find. I imagine this is more readable than writing a parser, but if you'd prefer changes here I'm OK with changing it. A side effect of this choice is that an invalid command like `:delmarks %f-h` will throw the error message `E475: Invalid argument: %fgh` rather than `E475: Invalid argument: %f-h` (because it has …

VIM-1720 Implement Ex command :delm[arks]

---

src/com/maddyhome/idea/vim/extension/surround/VimSurroundExtension.java
test/org/jetbrains/plugins/ideavim/extension/surround/VimSurroundExtensionTest.kt

https://github.com/tpope/vim-surround/blob/master/doc/surround.txt#L138
I noticed that this was missing from IdeaVim, and it seems very useful and not all that complicated, so I gave it a go.
... and it turned out to be somewhat complicated after all since `<C-F>` keystrokes are not caught by the current extension (which is based on pure characters, so `<C-F>` is ignored). I made an attempt to implement that as well here:
https://github.com/JetBrains/ideavim/compare/master...jorgengranseth:attempt-at-ctrl-f
While the test passes, it doesn't work in the IDE since `<C-F>` gets hijacked by IdeaVim as the page-down motion. Setting the key mapping to undefined didn't work - I'm not sure if this is a bug - but I am also not sure if this is the right approach since I haven't looked into other …

 Support f and F surround commands (function name)

---

src/com/maddyhome/idea/vim/extension/multiplecursors/VimMultipleCursorsExtension.kt
test/org/jetbrains/plugins/ideavim/extension/multiplecursors/VimMultipleCursorsExtensionTest.kt

With `ignorecase` enabled, select next (`<A-n>`) would get stuck on the
second occurrence even though there are more occurrences to select. This
was happening because part of logic was still doing case sensitive
comparison against the current pattern. The fix is to use case
insensitive comparator everywhere the pattern is used, if `ignorecase`
option is set.

Fix multiple cursors selection getting stuck with ignorecase

---

src/com/maddyhome/idea/vim/ex/vimscript/VimScriptParser.java

XDG config read implementation was changed to use invalid path separator.
This PR fixes this.

VIM-664 Fix usage of invalid path separator

---

resources/META-INF/includes/VimExtensions.xml
src/com/maddyhome/idea/vim/extension/argtextobj/VimArgTextObjExtension.java
test/org/jetbrains/plugins/ideavim/extesion/argtextobj/VimArgTextObjExtensionTest.java

This is a "port" of VIMs [argtextobj.vim](https://vim.sourceforge.io/scripts/script.php?script_id=2699) script. It adds two new text objects `ia` and `aa` that represent an function argument. This implementation also supports angle brackets and curly braces which is handy for C++ templates and Java generics and C++ brace initialization lists.

Add argtextobj.vim plugin emulation

---

README.md
src/com/maddyhome/idea/vim/extension/argtextobj/VimArgTextObjExtension.java
test/org/jetbrains/plugins/ideavim/VimTestCase.java
test/org/jetbrains/plugins/ideavim/extesion/argtextobj/VimArgTextObjExtensionTest.java

argtextobj by default only handles arguments inside parenthesis. This is
very limiting when editing C++ source files. This change allows the list
of bracket pairs to be configurable via a global IdeaVim variable. The
variable takes effect immediately.

argtextobj: support bracket pairs configuration via let g:argtextobj_pairs="..."

---

src/com/maddyhome/idea/vim/ui/ExTextField.java

When searching (using /) Chinese characters are displayed as a box surrounded by question marks.
[https://youtrack.jetbrains.com/issue/VIM-570](https://youtrack.jetbrains.com/issue/VIM-570)

fixed #VIM-570

---

src/com/maddyhome/idea/vim/KeyHandler.java

fix when use  >0  number register, treat it as a [count].but it is a  register.

[VIM-1991] fix >0 number register not work

---

src/com/maddyhome/idea/vim/group/MarkGroup.java

Currently we keep intelij navigation history separate from ideavim jumplist.
This change will cause all updates to ideavim jumplist to be propagated to intelij navigaration history as well.
https://youtrack.jetbrains.com/issue/VIM-44

Populate intelij navigation history together with ideavim jumplist

---

CHANGES.md
src/com/maddyhome/idea/vim/group/EditorGroup.java
src/com/maddyhome/idea/vim/group/MotionGroup.java
src/com/maddyhome/idea/vim/helper/EditorHelper.java

Instead of maintaining state to enable/disable smooth scrolling per-editor, when IdeaVim is enabled/disabled, this PR means IdeaVim supports smooth scrolling. All scrolling such as `<C-F>`  will be handled correctly, and the page is animated, as when IdeaVim is disabled. The "Enable smooth scrolling" option in _Preferences | Editor | General_ is now correctly respected by IdeaVim.

Support smooth scrolling

---

resources/META-INF/plugin.xml

Initialise early in the post startup activities so that any open editors get Vim features as soon as possible. This is most important on Rider, which has a post startup activity that blocks until Rider's project model is ready. Unfortunately, it also blocks plugin startup activities.
All core startup activities are unordered and don't have IDs, so all we can do is go first.

Prioritise startup activity to initialise IdeaVim early

---

src/com/maddyhome/idea/vim/group/EditorGroup.java

Use the new line number converter API to provide relative line numbers. This allows specifying the largest line number (the old API would get the converted line number of the last line, which could have a single digit, while the caret line could have multiple digits). This could also cause "flickering" as the expected width of the text gutter changes. Fixes [VIM-1934](https://youtrack.jetbrains.com/issue/VIM-1934) and [VIM-1852](https://youtrack.jetbrains.com/issue/VIM-1852).
Also fixes an issue where moving the text caret would re-initialise line numbers. Now it simply repaints. Fixes [VIM-2021](https://youtrack.jetbrains.com/issue/VIM-2021)

Use new API for relative line numbers

---

src/com/maddyhome/idea/vim/KeyHandler.java
test/org/jetbrains/plugins/ideavim/action/ResetModeActionTest.kt

Suppose we have the text "|Hello, world", with | being the position of
the cursor. Pressing `d<Esc>dw` simply moves the cursor on top of the
comma instead of leaving the text as ", world".
This fixes issue VIM-1421.
I'm creating the pull request again, since on rebasing I apparently messed up the history.

Reset operator-pending commands on escape

---

src/com/maddyhome/idea/vim/KeyHandler.java
test/org/jetbrains/plugins/ideavim/action/ResetModeActionTest.kt

This is a continuation on Adriafarres pull request (#237) since that PR has been idle for the past month and this bug really annoys me. I'll just quote the previous issue description:
> Suppose we have the text "|Hello, world", with | being the position of
the cursor. Pressing d<Esc>dw simply moves the cursor on top of the
comma instead of leaving the text as ", world".
>
> This fixes issue VIM-1421
I've added some more test cases based on the last comment in the other PR.
Please let me know what you think :)

Properly reset when pressing Esc in the middle of command

---

README.md

README shows this path that follows XDG standart
```
$XDG_CONFIG_HOME$/ideavim/ideavimrc
```
It should be 
```
$XDG_CONFIG_HOME/ideavim/ideavimrc
```
Because be default **$XDG_CONFIG_HOME** points to $HOME/.config and I can to `cd $XDG_CONFIG_HOME` but `cd $XDG_CONFIG_HOME$`  will show this error `no such file or directory: /home/username/.config$`

Fix alternative XDG path in README

---

resources/META-INF/includes/VimExCommands.xml
src/com/maddyhome/idea/vim/ex/handler/TabCloseHandler.kt

Hello, 
This PR implemented the `tabc[lose]` ex command to close a specific tab.
https://youtrack.jetbrains.com/issue/VIM-2068
---
🍺 usages:
```
:tabc[lose]   Close current tab page
:tabc[lose]{count}  Close tab page {count}. just like the classic vim:
:tabclose -2    " close the two previous tab page
:tabclose +     " close the next tab page
:tabclose 3     " close the third tab page
:tabclose $     " close the last tab page
```
🔔 notices:
- If there is only one tab page on the current active tabbed pane, then this tab will be closed, which is different from the classic vim.
- If the `{count}` parameter is out of range, then the nearest head or tail pane will be closed.
- If current tab has been closed, the focus state will be transfered to next tab, otherwise the current tab remains …

Implement tabc[lose] ex command

---

src/com/maddyhome/idea/vim/action/copy/PutTextAction.kt
src/com/maddyhome/idea/vim/ex/handler/PutLinesHandler.kt
src/com/maddyhome/idea/vim/ex/handler/RegistersHandler.kt
src/com/maddyhome/idea/vim/group/MacroGroup.java
test/org/jetbrains/plugins/ideavim/ex/handler/RegistersHandlerTest.kt

Add support for putting and editing a macros
https://youtrack.jetbrains.com/issue/VIM-2059
Currently we can't edit a recorded marco just like what we can do in classic vim.
What this PR does:
1. put a recorded macro to current buffer by converting key strokes to printable characters with `p` or `:put`
2. convert text to a collection of key strokes while playing back a macro
Effects :
1. can put recorded macro as printable character
2. support for editing macro (put from and yank to register)
3. can play back any register as a macro even if it's not a recorded macro, eg from yanking
I'm a idea & vim fanatic, ideavim saved my days! Thank you guys!

add support for putting & editing macros

---

doc/emulated-plugins.md
resources/META-INF/includes/VimExtensions.xml
src/com/maddyhome/idea/vim/extension/highlightedyank/VimHighlightedYank.kt
src/com/maddyhome/idea/vim/group/ChangeGroup.java
src/com/maddyhome/idea/vim/group/copy/YankGroup.kt
src/com/maddyhome/idea/vim/listener/VimInsertListener.kt
src/com/maddyhome/idea/vim/listener/VimYankListener.kt
test/org/jetbrains/plugins/ideavim/TestHelper.kt
test/org/jetbrains/plugins/ideavim/extension/highlightedyank/VimHighlightedYank.kt
test/org/jetbrains/plugins/ideavim/extension/highlightedyank/VimHighlightedYankTest.kt

Hey!
Before i go in I'd like to mention, that I've never contributed to any project before so if i did something wrong things please let me know :)
So, I've found issue ([VIM-1970](https://youtrack.jetbrains.com/issue/VIM-1970)) on plugin that is really simple but makes vim a little bit more pleasurable. This is vim-highlightedyank. I've been using it with Vim and it would be nice to have it in ideavim.
There was no response since that question and I decided to implement it myself.
Based on your advice (`or create a draft PR to indicate that you've started working`) I've created a draft PR to let you know that I've started working on this.
Right now I believe this draft is overall working version of the plugin. I was thinking if you have any thoughts on this solution.
It's still a draft …

VIM-1970 | Working solution of plugin vim-highlightedyank

---

src/com/maddyhome/idea/vim/group/EditorGroup.java

This is a fix for an `AlreadyDisposedException` in idea.log, unfortunately there was no repro case for this exception. The origin log is as follow:
```
2020-08-03 05:57:22,291 [57156550]  ERROR - tellij.openapi.util.ObjectTree - Cannot create com.intellij.ui.EditorNotifications because container is already disposed: Project(name=myproject, containerState=DISPOSE_COMPLETED, componentStore=<path-to-project>) 
com.intellij.serviceContainer.AlreadyDisposedException: Cannot create com.intellij.ui.EditorNotifications because container is already disposed: Project(name=myproject, containerState=DISPOSE_COMPLETED, componentStore=<path-to-project>)
at com.intellij.serviceContainer.ComponentManagerImpl.throwContainerIsAlreadyDisposed(ComponentManagerImpl.kt:445)
at …
```

Check if project is disposed when editorDeinit

---

src/com/maddyhome/idea/vim/action/motion/leftright/MotionArrowRightAction.kt
src/com/maddyhome/idea/vim/action/motion/updown/MotionArrowDownAction.kt
src/com/maddyhome/idea/vim/action/motion/updown/MotionArrowUpAction.kt
src/com/maddyhome/idea/vim/action/motion/updown/MotionDownActions.kt
src/com/maddyhome/idea/vim/action/motion/updown/MotionShiftDownAction.kt
src/com/maddyhome/idea/vim/action/motion/updown/MotionShiftUpAction.kt
src/com/maddyhome/idea/vim/action/motion/updown/MotionUpActions.kt
src/com/maddyhome/idea/vim/command/CommandState.kt
src/com/maddyhome/idea/vim/group/ChangeGroup.java
src/com/maddyhome/idea/vim/group/MotionGroup.java
src/com/maddyhome/idea/vim/handler/EditorActionHandlerBase.kt
src/com/maddyhome/idea/vim/handler/MotionActionHandler.kt
src/com/maddyhome/idea/vim/helper/CommandStateExtensions.kt
src/com/maddyhome/idea/vim/helper/EditorHelper.java
src/com/maddyhome/idea/vim/helper/EditorHelper.kt
src/com/maddyhome/idea/vim/helper/UserDataManager.kt
src/com/maddyhome/idea/vim/option/OptionsManager.kt
test/org/jetbrains/plugins/ideavim/VimTestCase.kt
test/org/jetbrains/plugins/ideavim/action/change/delete/DeleteVisualLinesEndActionTest.kt
test/org/jetbrains/plugins/ideavim/action/motion/leftright/MotionRightActionTest.kt
test/org/jetbrains/plugins/ideavim/action/motion/updown/MotionArrowDownActionTest.kt
test/org/jetbrains/plugins/ideavim/action/motion/visual/VisualToggleCharacterModeActionTest.kt
test/org/jetbrains/plugins/ideavim/extension/CommonExtensionTests.kt

This does not support all config settings,
but does add the 'onemore' option.
This partly addresses https://youtrack.jetbrains.com/issue/VIM-844

Partial implementation of virtualedit config

---

CHANGES.md
src/com/maddyhome/idea/vim/group/MotionGroup.java
src/com/maddyhome/idea/vim/helper/EditorHelper.java
src/com/maddyhome/idea/vim/listener/VimListenerManager.kt
test/org/jetbrains/plugins/ideavim/VimTestCase.kt
test/org/jetbrains/plugins/ideavim/group/motion/MotionGroup_scrolloff_scrolljump_Test.kt

Top tip: if you're looking for a good example file to test rendered doc comments, then `String.java` is a good place to go.

Fix various scrolling issues

---

src/com/maddyhome/idea/vim/group/RegisterGroup.java
test/org/jetbrains/plugins/ideavim/action/CopyActionTest.java

I'm not all that confident about the fix -- it's quite hard to follow Vim code here -- but it results in behavior matching Vim and all tests still pass.
Note that it depends on #249 due to another bug in this simple scenario.

VIM-2114 Do not override registers when deleting empty range

---

src/com/maddyhome/idea/vim/KeyHandler.java
src/com/maddyhome/idea/vim/group/EditorGroup.java
src/com/maddyhome/idea/vim/group/visual/VisualGroup.kt
src/com/maddyhome/idea/vim/listener/VimListenerManager.kt

Hi,
This is my first pull request here, and for an Idea plugin in general, and I admit I don't know the API very well. So, please tell me what do you think first, and if something's not right, feel free to point it out or close the PR.
Currently IdeaVim always uses block caret for normal mode, and bar caret for insert mode. This commit introduces a new `.ideavimrc` option named "ideacursor", which can hold an array of "bar" and "block" properties. User can choose which caret style can be used for normal and insert mode by specifying 'bar' or 'caret' in this option:
set ideacursor=<insert caret style>,<normal caret style>
For example:
set ideacursor=block,bar
This option will instruct IdeaVim to display block caret in insert mode, and bar caret in normal node. The second argument is …

VIM-1475: Add an option to use block caret in insert mode

---

src/com/maddyhome/idea/vim/helper/CharacterHelper.kt
test/org/jetbrains/plugins/ideavim/action/MotionActionTest.java

- Add unicode CJK Unified Ideographs type
- Stop caret movement for CJK chars (as VIM does). Similar to [VIM-58](https://youtrack.jetbrains.com/issue/VIM-58)

Add CJK characterType for delimiting caret movement

---

src/com/maddyhome/idea/vim/KeyHandler.java
src/com/maddyhome/idea/vim/command/CommandBuilder.kt
src/com/maddyhome/idea/vim/ui/ExEditorKit.java
src/com/maddyhome/idea/vim/ui/ExShortcutKeyAction.kt
src/com/maddyhome/idea/vim/ui/ExTextField.java
test/org/jetbrains/plugins/ideavim/VimTestCase.kt
test/org/jetbrains/plugins/ideavim/action/MotionActionTest.java
test/org/jetbrains/plugins/ideavim/ex/ExEntryTest.kt

I implemented c[nore]map partially. It would be ideal if I could fully, but it seems to need a lot of work.
It's partial because
- cmap can't be set in the command line unless it's written in ideavimrc or listed in ExKeyBindings.kt
- cmap only supports one-to-many keycaps, e.g. `cmap <C-a><C-b> <Home>` is impossible

Implement cmap

---

src/com/maddyhome/idea/vim/key/MappingInfo.kt

Small fix to show the correct handler class name in the output of `:map`, instead of all handlers showing `call com.maddyhome.idea.vim.key.ToHandlerMappingInfo`

Show the correct handler class in :map

---

resources/META-INF/includes/VimActions.xml
src/com/maddyhome/idea/vim/action/motion/scroll/MotionScrollPageDownAction.kt
src/com/maddyhome/idea/vim/action/motion/scroll/MotionScrollPageUpAction.kt
src/com/maddyhome/idea/vim/action/motion/text/MotionWordLeftAction.kt
src/com/maddyhome/idea/vim/action/motion/text/MotionWordRightAction.kt

With ideavimrc settings
set selectmode+=key
set keymodel^=startsel
arrow keys and home/end allow selection in insert mode.  
This appears to be the correct fix to me.  Open to suggestions

VIM-1756: startSel works in insert mode

---

src/com/maddyhome/idea/vim/helper/EditorHelper.kt

to provide compatibility with Code With Me plugin
ONLY for Idea versions 202, 203 and newer. These changes are now compatible with 201 and older.

CWM-927 disable vim for client's hidden editor on host

---

src/com/maddyhome/idea/vim/group/SearchGroup.java
src/com/maddyhome/idea/vim/helper/SearchHelper.java
src/com/maddyhome/idea/vim/helper/SearchHelperKt.kt
src/com/maddyhome/idea/vim/helper/SearchHighlightsHelper.kt

Continuing the groundwork for [VIM-2173](https://youtrack.jetbrains.com/issue/VIM-2173) that began in #257, this PR refactors `SearchGroup`. There are no code changes, only moving methods around. This is a separate PR to make the next PR easier to review - it will be making code changes without moving things around :smile: 
* Static "find" methods are moved to `SearchHelper`. The methods in `SearchGroup` are now the "high level" APIs to implement Vim's search and replace functionality. They maintain state, parse commands and call into `SearchHelper` to do the actual searching.
* Rearrange and document the APIs in `SearchGroup` to better understand what the methods are doing (there are quite a few overloads simply called `search` that do different things with state and carets, etc.)
* …

Refactor SearchGroup

---

src/com/maddyhome/idea/vim/group/MotionGroup.java
test/org/jetbrains/plugins/ideavim/action/motion/updown/MotionGotoLineLastActionTest.kt

Fixes [VIM-2291](https://youtrack.jetbrains.com/issue/VIM-2291). If a file has any folds (most Java or Kotlin files) and `scrolloff` > 0 and the caret is within `scrolloff` lines of the bottom of the file, the screen is incorrectly scrolled to put the last line at the bottom of the screen. This is due to mixing up logical lines and visual lines.

Fix scrolling at end of file with folds

---

resources/dictionaries/ideavim.dic
resources/messages/IdeaVimBundle.properties
src/com/maddyhome/idea/vim/VimPlugin.java
src/com/maddyhome/idea/vim/ex/handler/CmdFilterHandler.kt
src/com/maddyhome/idea/vim/group/ProcessGroup.java
src/com/maddyhome/idea/vim/option/OptionsManager.kt
src/com/maddyhome/idea/vim/option/StringOption.java

This PR fixes a few issues with the filter (`:!`) command:

VIM-1357+VIM-1566: Use OS shell to run filter command

---

.github/workflows/runUiTests.yml
AUTHORS.md
build.gradle.kts
gradle.properties
test/ui/UiTests.kt
test/ui/pages/Editor.kt
test/ui/pages/IdeaFrame.kt
test/ui/utils/JavaExampleSteps.kt
test/ui/utils/UiTestWrapper.kt
test/ui/utils/Utils.kt

Added runUiTest config
Fixed UI test
Fixed all Ide Errors which were caused by the test(invokeLater, runWriteAction, runOnEdt)
Saving screenshot and report if UI test fails
Updated version of remote-fixture(now it is published with remote-robot and has the same version)

Run UI test ci

---

src/main/java/com/maddyhome/idea/vim/group/MotionGroup.java
src/main/java/com/maddyhome/idea/vim/helper/EditorHelper.java
src/test/java/org/jetbrains/plugins/ideavim/action/scroll/ScrollHalfPageDownActionTest.kt
src/test/java/org/jetbrains/plugins/ideavim/action/scroll/ScrollHalfPageUpActionTest.kt

Fixes [VIM-2432](https://youtrack.jetbrains.com/issue/VIM-2432). `<C-U>` and `<C-D>` would not place the caret on the very first or very last line of the file when `'scrolloff'` was set. Also, `<C-D>` would introduce virtual space rather than keep the last line of the file at the bottom of the screen (unless virtual space was already there, in which case it wouldn't scroll at all).

fix(VIM-2432): handle scrolloff with <C-D> and <C-U>

---

src/main/java/com/maddyhome/idea/vim/group/EditorGroup.java
src/main/java/com/maddyhome/idea/vim/helper/CaretVisualAttributesHelper.kt
src/test/java/org/jetbrains/plugins/ideavim/helper/CaretVisualAttributesHelperTest.kt

Fixes [VIM-2462](https://youtrack.jetbrains.com/issue/VIM-2462)

Reset caret shape when disabling plugin

---

.github/workflows/runUiTests.yml
CHANGES.md
build.gradle.kts
src/test/java/ui/UiTests.kt

you can check the example of video in [this run](https://github.com/nizienko/ideavim/actions/runs/1449975763)

Video recording for ui tests

---

gradle.properties

JVM on Windows doesn't use UTF-8, so compilation of unit test sources with special characters fails on Windows:
```
assertIsKeyword('Ā');
// unclosed character literal
// unclosed character literal
// not a statement
```
Discussion: https://github.com/JetBrains/ideavim/discussions/389
Unfortunately I don't know how to fix the `doc` folder containing files with quotes, which are illegal on Windows. In case anyone finds this, all I can recommend is this command to remove the `doc` folder altogether, so that `git status` doesn't constantly complain about missing files:
```
git submodule deinit -f doc
```

Fix compile errors in unit tests on Windows

---

src/main/java/com/maddyhome/idea/vim/extension/matchit/Matchit.kt

Rebased the changes from #421 to master.
This feature adds support for single file Vue components which have its own .vue-extension and are a "mixture" of a HTML-Template, JavaScript- and CSS-code. (A bit similar to JSX-files...)
With this added "Vue.js" fileType they work now as expected.

Add Matchit support for Vue.js files

---

src/main/java/com/maddyhome/idea/vim/extension/surround/VimSurroundExtension.kt
src/test/java/org/jetbrains/plugins/ideavim/extension/surround/VimSurroundExtensionTest.kt

Hi there!
This PR adds support for custom elements (e.g. `<custom-element></custom-element>`) to the vim-surround extension. Let me know if I should change something.
Thanks a lot for creating this plugin. I like it a lot!

Support custom element names in vim-surround

---

src/main/java/com/maddyhome/idea/vim/group/ProcessGroup.java

I noticed that whenever try to run a local command: ":! something" only stdout gets printed.
In `vim/nvim` both `stderr` and `stdout` get printed. We can fix this with this PR.
TODO:

Print stderr when running a command just like vim does

---

src/main/java/com/maddyhome/idea/vim/option/GuiCursorOption.kt
src/main/java/com/maddyhome/idea/vim/vimscript/model/options/helpers/GuiCursorOptionHelper.kt
src/test/java/org/jetbrains/plugins/ideavim/VimTestCase.kt
src/test/java/org/jetbrains/plugins/ideavim/helper/CaretVisualAttributesHelperTest.kt
src/test/java/org/jetbrains/plugins/ideavim/option/GuiCursorOptionTest.kt

Fixes [VIM-2470](https://youtrack.jetbrains.com/issue/VIM-2470). Setting the `'guicursor'` option to include an `a:` mode ("all") without specifying a cursor shape would overwrite existing cursor shapes for other modes with "block".
After this change, a missing cursor shape will no longer override. If all modes are missing, then the default block is used.

fix(VIM-2470): Fix incorrect reset of cursor shape

---

doc/ideajoin-examples.md

I didn't find which shortcut to use in order to activate `ideajoin`.
I checked the [source code](https://github.com/JetBrains/ideavim/blob/master/src/test/java/org/jetbrains/plugins/ideavim/action/change/delete/DeleteJoinLinesSpacesActionTest.kt) to find that is `shift+j`
This PR update the documentation with that information.
And thanks for this fantastic plugin, I use it for years and I cannot use any other IDEs given how good this plugin is ❤️

Add shortcut to ideajoin example

---

src/main/java/com/maddyhome/idea/vim/helper/EditorDataContext.kt

This PR fixes Hannah-Sten/TeXiFy-IDEA#2230
* In `build.gradle.kts`, add a dependency on plugin [TeXiFy-IDEA](https://github.com/Hannah-Sten/TeXiFy-IDEA): `nl.rubensten.texifyidea:0.7.14`
* `runIde`
* Go to Settings > Editor > Code Style, set `Hard wrap at` to 120 characters and enable `Wrap on typing`.
* Create a LaTeX file (`.tex`) and paste the following content:
```tex
\begin{itemize}
\item This is the first item: pressing enter at the end of this line will insert an \verb|\item| on the next line.
\item This line should hard-wrap to a next line without inserting an \verb|\item| in front of it, when typing here:
\end{itemize}
```
* Continue typing after `... when typing here:`
* Expected behaviour, and this is what happens when IdeaVim is not installed: the text is wrapped to the next …

Implement UserDataHolder for EditorDataContext

---

src/main/java/com/maddyhome/idea/vim/group/SearchGroup.java
src/test/java/org/jetbrains/plugins/ideavim/ex/implementation/commands/SubstituteCommandTest.kt

We need to set newend after the content of match is final, otherwise we
can end up in an endless loop. This allows us to remove the
startoff != latestOff check that previously prevented this endless
loop and caused this bug.

Fix(VIM-2553): Substitute consecutive matches

---

src/main/java/com/maddyhome/idea/vim/extension/matchit/Matchit.kt
src/test/java/org/jetbrains/plugins/ideavim/extension/matchit/MatchitCMakeTest.kt
src/test/java/org/jetbrains/plugins/ideavim/extension/matchit/MatchitCTest.kt
src/test/java/org/jetbrains/plugins/ideavim/extension/matchit/MatchitGNUMakeTest.kt
src/test/java/org/jetbrains/plugins/ideavim/extension/matchit/MatchitGeneralTest.kt
src/test/java/org/jetbrains/plugins/ideavim/extension/matchit/MatchitRubyTest.kt

Following up on https://github.com/JetBrains/ideavim/pull/343, this PR adds Matchit support for the C family of languages. The plugin now supports jumps on C-style preprocessor directives (found in C, C++, C#, ObjC), Makefiles, and CMake files.
I also refactored the code to be simpler and to make language configuration easier. Sorry for the large diff though! The changes are split into distinct commits with more detailed notes in the commit messages.
To sum up, I:
- Simplified the search code in `findClosingPair()` and `findOpeningPair()`
- Refactored `parsePatternAtOffset()` to return both the pattern start and end offsets
- This is was necessary to support the `else if` conditional in Makefiles
- Created the `LanguagePatterns` class to make language configuration easy
- The new …

Add Matchit support for the C family of languages

---

src/main/java/com/maddyhome/idea/vim/group/MotionGroup.java
src/main/java/com/maddyhome/idea/vim/helper/EditorHelper.java
src/main/java/com/maddyhome/idea/vim/vimscript/services/OptionServiceImpl.kt

This PR fixes a couple of tiny bugs:

Minor bug fixes

---

src/main/java/com/maddyhome/idea/vim/helper/EditorHelper.java
src/test/java/org/jetbrains/plugins/ideavim/VimTestCase.kt
src/test/java/org/jetbrains/plugins/ideavim/action/scroll/ScrollFirstScreenColumnActionTest.kt
src/test/java/org/jetbrains/plugins/ideavim/action/scroll/ScrollLastScreenColumnActionTest.kt
src/test/java/org/jetbrains/plugins/ideavim/group/motion/MotionGroup_ScrollCaretIntoViewHorizontally_Test.kt
src/test/java/org/jetbrains/plugins/ideavim/helper/EditorHelperTest.kt

The default font for the `corretto-11` JDK (at least on my Mac) is Menlo 12 point. This results in nice 8 pixel character widths and integer maths. If `jbr-11` is used, the font is JetBrains Mono 13 point, which has characters that are 7.8 pixels wide (I don't know why a larger font has a smaller pixel side, but that's not really the problem here). 
Most APIs to work with editor positions uses integers, which can cause rounding errors. I don't think this caused any obvious issues in production - possibly some minor off-by-one (or two) errors in column positioning, but it does cause issues with tests, where we need reproducibility.
This PR updates `EditorHelper` to overcome rounding errors in scrolling, and updates tests to correctly calculate expected offsets. Tests now run on both …

Improve handling of fractional width fonts

---

src/main/java/com/maddyhome/idea/vim/listener/IdeaSpecifics.kt

Works ok with insertions (Enter, Ctrl+Enter) but not with replacements (Tab). It also breaks if the code completion modifies imports.
I did this a while back to improve the situation with https://youtrack.jetbrains.com/issue/VIM-913. I hoped there would be a better solution that would cover all possible cases including replacements and imports, but this half-fix is better than nothing :P

Implement partial code completion support in macros

---

src/test/java/org/jetbrains/plugins/ideavim/RegisterActionsTest.kt
src/test/java/org/jetbrains/plugins/ideavim/VimTestCase.kt
src/test/java/org/jetbrains/plugins/ideavim/action/change/insert/InsertNewLineBelowActionTest.kt
src/test/java/org/jetbrains/plugins/ideavim/action/change/insert/VisualBlockInsertActionTest.kt
src/test/java/org/jetbrains/plugins/ideavim/action/motion/search/SearchAgainPreviousActionTest.kt
src/test/java/org/jetbrains/plugins/ideavim/action/motion/updown/MotionUpActionTest.kt
src/test/java/org/jetbrains/plugins/ideavim/ex/CommandParserTest.kt
src/test/java/org/jetbrains/plugins/ideavim/extension/matchit/MatchitCMakeTest.kt
src/test/java/org/jetbrains/plugins/ideavim/extension/matchit/MatchitCTest.kt
src/test/java/org/jetbrains/plugins/ideavim/extension/matchit/MatchitGNUMakeTest.kt
src/test/java/org/jetbrains/plugins/ideavim/extension/matchit/MatchitGeneralTest.kt
src/test/java/org/jetbrains/plugins/ideavim/extension/matchit/MatchitRubyTest.kt

Updates `VimTestCase.kt` to consolidate the various `doTest` functions so everything eventually goes through one `doTest` function. `@JvmOverloads` are added for Java tests, and default arguments means it is no longer necessary to specify the default modes of `COMMAND`/`NONE` at all call sites (not removed in existing tests). Also fixes a minor bug in one of the deleted `doTest` overloads that would pass keys to neovim twice (was fortunately never called).
This is groundwork for extending `doTest` to support testing wrapped and folded text without having to use offsets.

Consolidate doTest methods

---

src/main/java/com/maddyhome/idea/vim/group/EditorGroup.java
src/main/java/com/maddyhome/idea/vim/newapi/IjVimEditor.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/action/motion/visual/VisualSelectPreviousAction.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/action/motion/visual/VisualSwapSelectionsAction.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/api/VimEditor.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/common/VimScrollType.kt

Previously, IdeaVim would enable the "refrain from scrolling" setting in each editor. This appears to be historical, as all IdeaVim scrolling is explicit and to an exact location. This setting now only affects the scroll location when IntelliJ navigates, such as with Go To Member when the target is already visible.
The default setting is "keep the caret in place, scroll editor canvas" (refrain from scrolling disabled - hooray for double negatives!), which will scroll the editor and place the caret about 1/3rd of the way down the editor. IdeaVim would previously override this to "move caret, minimise editor scrolling", which will move the caret without scrolling if the target is already visible.
Even though this overridden behaviour is more Vim-like (Vim prefers to move the caret if the …

Fix(VIM-2778) Remove override of editor scroll setting 

---

src/test/java/org/jetbrains/plugins/ideavim/action/motion/updown/MotionDownActionTest.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/api/VimMotionGroupBase.kt

When moving down from a long line to a shorter line that has an end-of-line inlay hint, the offset was incorrectly normalised by the action. In strict mode, the motion handler asserts that the action normalised the offset correctly, which prevents the motion from occurring.

Fix incorrect normalising for trailing inlay

---

src/test/java/org/jetbrains/plugins/ideavim/action/copy/PutTestAfterCursorActionTest.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/put/VimPutBase.kt

Improves the situation at [VIM-2577](https://youtrack.jetbrains.com/issue/VIM-2577/PyCharm-2021.3-EAP-IdeaVim-1.10.0-Cannot-paste-at-end-of-cell) with the same "fix" that is done at the end of the file.
Technically that behavior is not the same as in vim. Pasting at the end of the file should not result in an empty line bellow the inserted text.

Fix(VIM-2577) paste not working at end of notebook cell

---

src/main/java/com/maddyhome/idea/vim/EventFacade.java
src/main/java/com/maddyhome/idea/vim/helper/UserDataManager.kt
src/main/java/com/maddyhome/idea/vim/listener/VimListenerManager.kt
src/main/java/com/maddyhome/idea/vim/ui/ex/ExEntryPanel.java
src/test/java/org/jetbrains/plugins/ideavim/action/motion/leftright/MotionLastColumnActionTest.kt

Fixes a couple of issues:
* Fixes an issue with incremental search not scrolling to the current match. The caret was being moved using the platform's `moveToOffset` rather than IdeaVim's, which also handles scrolling
* Fixes an issue with remembering the "end of line" state for `$` not invalidating if the caret was moved and then moved back to its previous location. E.g. `$hlj` would act like `$j` and put the caret at the end of the next line, rather than simply moving down to the same column

Fix incremental search not scrolling to current match

---

src/main/java/com/maddyhome/idea/vim/helper/HandlerInjector.kt

Hi,
I tried to fix  [VIM-2760](https://youtrack.jetbrains.com/issue/VIM-2760/Jupyter-Notebooks-unable-to-enter-the-edit-mode-with-keyboard-after-pressing-Esc) because it really annoyed me :D
`notebookCommandMode` always returns false which results in handling the enter key wrong when in command mode of the notebook.
I tried to fix that by checking the client property ActionUtil.ALLOW_PlAIN_LETTER_SHORTCUTS that is set by [NotebookEditorModeListenerAdapter](https://github.com/JetBrains/intellij-community/blob/323891923c39ffb58a8e760c03ec4de0f4c9e4ca/notebooks/notebook-ui/src/org/jetbrains/plugins/notebooks/ui/editor/actions/command/mode/NotebookEditorMode.kt#L93).
I don't know if this is just a hack or a viable way to do it.
Another option to fix the issue would be to create our own …

Fix(VIM-2760) notebookCommandMode detection

---

src/main/java/com/maddyhome/idea/vim/extension/matchit/Matchit.kt

This enables HTML jumps in [Razor templates][razor] to fix [VIM-2799][issue]. I confirmed this works in the latest version of Rider.
[issue]: https://youtrack.jetbrains.com/issue/VIM-2799/matchit-support-for-cshtml-files
[razor]: https://learn.microsoft.com/en-us/aspnet/core/mvc/views/razor?view=aspnetcore-7.0

VIM-2799: Add Matchit support for cshtml files

---

src/main/java/com/maddyhome/idea/vim/extension/matchit/Matchit.kt

Rider supports a few other file types that are flavors of HTML/XML:
- `Asp`: templating language for .NET web apps, Razor's predecessor
- `UXML`: XML files for Unity game development
- `Xaml`: XML files for .NET Core UI development 
I should have included these in https://github.com/JetBrains/ideavim/pull/579, but I'm not a C# guy so they're new to me. 🙂

Matchit: Add more Rider file types

---

src/main/java/com/maddyhome/idea/vim/ui/Tutor.kt

Fixed some minor reference issues in the Tutor

Fixed number references in Tutor

---

src/main/java/com/maddyhome/idea/vim/listener/VimListenerManager.kt

A fix for an [issue](https://youtrack.jetbrains.com/issue/VIM-2773/Undoing-line-block-deletion-of-text-thats-immediately-followed-by-a-space-forces-the-editor-to-scoll-upwards) I raised on YouTrack.
In Vim, when starting a selection from an empty line and dragging backwards (or vertically upwards), the entirety of the empty line (including the EOL character) should be included as part of the selection. Hence when deleting the block, the empty line should also get removed. IdeaVim didn't adhere to this behaviour. This PR fixes it.
Before:
After:

VIM-2773: Include empty lines in the selection when dragging backwards from EOL

---

src/main/java/com/maddyhome/idea/vim/helper/UndoRedoHelper.kt
src/main/java/com/maddyhome/idea/vim/newapi/IjVimEditor.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/api/VimEditor.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/api/VimScrollingModel.kt

Small bug fix for [VIM-2773](https://youtrack.jetbrains.com/issue/VIM-2773/Undoing-text-deletion-forces-the-editor-view-upwards-when-deleted-from-Visual-Line-or-via-dd) which I raised on YouTrack.
Fixes viewport displacement when undoing deletion of lines or blocks that are immediately followed by a space character.
Before:
After:

VIM-2773: Prevent viewport displacement on undo

---

src/main/java/com/maddyhome/idea/vim/helper/SearchHelper.java
src/test/java/org/jetbrains/plugins/ideavim/action/motion/updown/MotionPercentOrMatchActionTest.kt

A fix for an issue I reported on YouTrack.
The Issue link is:
https://youtrack.jetbrains.com/issue/VIM-2887/action-leads-to-unexpected-destination-in-codes-containing-escaped-parentheses
I did `%` several times on parentheses below moives.
https://user-images.githubusercontent.com/45124565/223920790-4fd2bfd5-e974-4e48-9fc0-ac3fb55007d4.mp4
https://user-images.githubusercontent.com/45124565/223920819-d58b4501-108c-4d75-aa4d-8f5798a8a4b0.mp4

VIM-2887: Fix:Include escaped character in search target

---

doc/IdeaVim Plugins.md

It was pointing to the wrong plugin to install

Fix quick-scope setup documentation

---

src/main/java/com/maddyhome/idea/vim/VimPlugin.java

If you open the IDE but exit without loading the project.
<details open>
<summary>StackTrace</summary>
<pre>
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'disposable' of com/intellij/openapi/util/Disposer.dispose must not be null
at com.intellij.openapi.util.Disposer.$$$reportNull$$$0(Disposer.java)
at com.intellij.openapi.util.Disposer.dispose(Disposer.java)
at com.maddyhome.idea.vim.VimPlugin.turnOffPlugin(VimPlugin.java:358)
at com.maddyhome.idea.vim.VimPlugin.dispose(VimPlugin.java:107)
at com.intellij.openapi.util.ObjectTree.runWithTrace(ObjectTree.java:127)
at com.intellij.openapi.util.ObjectTree.executeAll(ObjectTree.java:159)
at com.intellij.openapi.util.Disposer.dispose(Disposer.java:264)
at com.intellij.openapi.util.Disposer.dispose(Disposer.java:252)
at …

Fix `dispose` operation

---

src/main/java/com/maddyhome/idea/vim/extension/matchit/Matchit.kt
src/test/java/org/jetbrains/plugins/ideavim/extension/matchit/MatchitHtmlTest.kt

This fixes some Matchit edge cases.
**Missed jumps on comments**
Currently, hitting `%` on the whitespace before a commented pair will not jump. This is a logic bug. When deciding if comments should be included in the search, we need to check the PSI element at the first match offset, not the caret offset.
As a bonus, this fix makes the special `isHtmlAttribute` check unnecessary. If the caret is in an HTML attribute, the first match offset will point to the start of the tag.
**Incorrect jumps on HTML tags sharing a prefix**
The regex for HTML jumps needs a closing `>` else a tag like `<Box>` will match with e.g. `<BoxHeading>`.
**[VIM-2905][link]: Matchit doesnt work with closing JSX tags**
[link]: https://youtrack.jetbrains.com/issue/VIM-2905/Matchit-doesnt-work-with-closing-JSX-tags
In …

Matchit bug fixes

---

src/main/java/com/maddyhome/idea/vim/group/ChangeGroup.java
src/test/java/org/jetbrains/plugins/ideavim/ex/implementation/commands/SortCommandTest.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/api/VimChangeGroup.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/vimscript/model/commands/SortCommand.kt

1. support `sort u`
2. fix natural sort issue when both string not contain number
3. refactored `SortCommandTest`

VIM-2615 add support to sort u command

---

src/test/java/org/jetbrains/plugins/ideavim/action/change/delete/DeleteMotionActionTest.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/action/motion/leftright/MotionLastMatchCharAction.kt

When doing repeat delete of find/till,
MotionType is determined by actually motion direction
- `t`,`f` -> Forward -> Inclusive
`T`,`F` -> Backward -> Exclusive
- `,` will reverse direction 
`;` will not.

VIM-1990 fix repeat delete find or till wrong MotionType

---

src/main/java/com/maddyhome/idea/vim/extension/matchit/Matchit.kt
src/test/java/org/jetbrains/plugins/ideavim/extension/matchit/MatchitPhpTest.kt

This adds the [Matchit patterns][ftplugin-link] required for PHP language support. PHP was requested in [VIM-2678][2678] and [VIM-2937][2937].
The unit test file is long since the language has a lot of patterns, but the motions themselves are straightforward. I made some small refactorings with notes in the earlier commits.
[2678]: https://youtrack.jetbrains.com/issue/VIM-2678/matchit-is-not-working-in-some-file-format
[2937]: https://youtrack.jetbrains.com/issue/VIM-2937/Matchit-doesnt-work-for-PHP-files
[ftplugin-link]: https://github.com/vim/vim/blob/46acad7284cba7842b5e505fa3d07e99806d246f/runtime/ftplugin/php.vim#L84

Add Matchit support for PHP 

---

src/main/java/com/maddyhome/idea/vim/helper/SearchHelper.java
src/test/java/org/jetbrains/plugins/ideavim/action/motion/object/MotionInnerBlockParenActionTest.kt
src/test/java/org/jetbrains/plugins/ideavim/helper/SearchHelperTest.kt

1. Fix block select expansion when there is line break after open(e.g "(") or before close (e.g. ")") 
2. Add test to cover `findBlockRange` function, so we have more confidence in later refactoring
3. Add Javadoc for easier understanding `findBlockRange`

VIM-2920 fix select block expansion when enclose boundary is line break

---

src/main/java/com/maddyhome/idea/vim/ui/ExOutputPanel.java
src/test/java/org/jetbrains/plugins/ideavim/VimTestCase.kt
src/test/java/org/jetbrains/plugins/ideavim/ex/implementation/commands/SetCommandTest.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/vimscript/model/commands/SetCommand.kt

This PR fixes a few minor formatting issues with the output of the `:set` command:
* It removes the trailing spaces added to the end of the line for column padding
* It sorts option names before formatting, so the `no` prefix for boolean options isn't included
* Options with values (`scrolloff=5`) are formatted with a 2 char indent to line up with the boolean options
* Long options are not wrapped by the formatter, but expected to be wrapped by the output pane. The formatter doesn't have the actual width of the output pane, only the character width of the editor, which doesn't include line numbers and gutter width. The output pane can enable soft wraps to provide better wrapping
* Output in the same order as Vim, filling each column in turn, rather than filling multiple columns …

Improve formatting of `:set` command output

---

src/main/java/com/maddyhome/idea/vim/group/EditorGroup.java
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/action/change/insert/InsertExitModeAction.kt

When initialising a new editor, IdeaVim will automatically start INSERT mode for an editor that is not a primary editor - that is, it's not file-backed, so it's not a main editor in the content area of the IDEA. This provides a more intuitive "just start typing" experience for editors that are more likely to be part of the UI than editing files, e.g. the VCS commit message editor.
IdeaVim would check that the editor was not file-backed, and that the document was writable, and then start INSERT mode. However, it is not enough that the document is writable, the editor needs to be non-read-only, too. Log and console output for run configurations and tests will have a writable document (because the app is updating it while the file is being externally modified), but the editor is in "viewer" …

Do not enter INSERT mode for read-only editors

---

src/main/resources/META-INF/plugin.xml

The 2023.2 platform requires `statusBarWidgetFactory` to have an `id` attribute in `plugin.xml`. This must be set to the same value returned by `StatusBarWidgetFactory.getId()`. If this value is missing, then hiding the status bar widget through the right click menu and then trying to show it again will fail.

Fix issue adding back hidden status bar widget

---

doc/Home.md
doc/IdeaVim Plugins.md

Hi 
I've been browsing through the doc and come across some broken markdown links:
https://github.com/JetBrains/ideavim/blob/master/doc/Home.md
so I've decided to grab my chance to become an open source contributor :) 
It ain't much just some boy scout rule applied

Fix md links in doc

---

src/main/java/com/maddyhome/idea/vim/action/VimActionConfigurationCustomizer.kt
src/main/resources/META-INF/plugin.xml

The 2023.3 IntelliJ Platform introduces an action called `ShowHoverInfo` that can be used to show the same tooltip which is displayed when the mouse hovers over a code symbol. This PR adds an extension point that will register an action with the same name for IntelliJ Platform versions that don't support this action. Once the base required version is raised to 2023.3, then this customisation can be removed, and all existing mappings will still work.
The base required version is raised to 2023.1 RTM to allow using the required platform API for the new action. It was on a preview version of 2023.1.
Users can invoke the action from a mapping, such as:
```vimL
nmap gh <Action>(ShowHoverInfo)
```
This PR fixes [VIM-2106](https://youtrack.jetbrains.com/issue/VIM-2106/Go-hover)

Add support for ShowHoverInfo action to 2023.1 and 2023.2

---

src/main/java/com/maddyhome/idea/vim/vimscript/model/functions/handlers/HasFunctionHandler.kt

I tried to replicate the logic from https://github.com/vim/vim/blob/0f058d13206665bad37c7d42834cfa0075f50239/src/evalfunc.c#L5511, not 100% sure if I got it right (and some special cases like `win32unix` are missing) but hopefully it's ok.

Add operating system type to `has()` function

---

src/main/java/com/maddyhome/idea/vim/group/FileGroup.java

Vim supports `~/` and `~\` on all platforms. This PR helps my muscle memory so I can type `:e ~/.ideavimrc` on Windows and it works the same in both IdeaVim and Vim.
Vim supports backslashes on Unix (tested on Vim) but both forward- and back-slashes on Windows. VFS supports both forward- and back-slashes on all platforms.

Support `~/` on Windows

---

src/main/java/com/maddyhome/idea/vim/ui/ReloadVimRc.kt
src/main/java/com/maddyhome/idea/vim/vimscript/Executor.kt

Found two issues related to [VIM-2933](https://youtrack.jetbrains.com/issue/VIM-2933):
1. Clicking the Reload button did not call `VimExtensionRegistrar.enableDelayedExtensions()`, so new extensions were not getting initialized.
At this point, there are 3 places in the code that follow the pattern of setting the `vimscriptExecutor.executingVimscript` flag, executing a script, and then initializing new extensions. On the other hand, the `:source` command does not appear to do this at all, it just executes the script and initializes extensions immediately.
I don't know why extensions have to be delayed, but it seems like the inconsistency and duplication of this behavior should be refactored. If this behavior exists at all, isn't it always necessary? - In which case the delayed …

Fix(VIM-2933): Reloading/sourcing .ideavimrc does not initialize new plugins

---

src/main/java/com/maddyhome/idea/vim/group/MacroGroup.kt

When running a macro with "Code Completion - Show suggestions as you type" enabled, it queues up the code completion popup to appear which causes a few issues:
- It happens even when the macro ends in normal mode, preventing keys such as Enter from executing their usual normal mode mapping because the popup steals them
- It prevents "Add unambiguous imports on the fly" from running, so as long as macros don't support imports ([VIM-2712](https://youtrack.jetbrains.com/issue/VIM-2712/Macros-dont-work-well-with-autocompletion-and-import)) it makes using macros across many files really slow, because after every macro run I have to press Escape and then wait
The PR stops code completion popup from being scheduled during a macro. The completion phase seems to get reinstated after every key, so …

Prevent code completion popup from appearing after running a macro

---

src/main/java/com/maddyhome/idea/vim/group/OptionGroup.kt
src/test/java/org/jetbrains/plugins/ideavim/option/EffectiveOptionChangeListenerTest.kt
src/test/java/org/jetbrains/plugins/ideavim/option/OptionAccessScopeTest.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/api/VimOptionGroup.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/api/VimOptionGroupBase.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/diagnostic/VimLogger.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/listener/ListenerSuppressor.kt

The `VimOptionGroupBase` class has become a bit of a god class/kitchen sink class. It has too many responsibilities, and is confusing to reason about. It handles setting/getting option values, initialising options for new windows and buffers, notifying listeners of changes and maintaining a cache of parsed effective values (e.g. parsing the contents of `'guicursor'`).
This PR splits the responsibilities into separate classes that `VimOptionGroupBase` uses. The classes are all implementation details, so remain in the same `VimOptionGroupBase.kt` file, but at least encapsulate responsibilities.
The majority of the changes are renames, extracting classes, and other similar refactoring. There is very little behaviour change, although a couple of minor bugs have been fixed.
This refactoring is …

Refactor VimOptionGroupBase

---

.idea/codeStyles/Project.xml

The project code style defaults to "System-dependent" line separator, and as I develop on Windows it means IDEA is giving me this warning and wants me to convert every file to CRLF, which imo doesn't make any sense. So this PR sets the code style to LF to make developing on Windows less annoying.

Enforce LF line separator in project code style

---

src/main/java/com/maddyhome/idea/vim/extension/matchit/Matchit.kt

Adds matchit support for `if/else`, `do/while`, and `try/catch/finally` statements in Java.

Add Matchit support for Java statements

---

src/main/java/com/maddyhome/idea/vim/action/change/OperatorAction.kt
src/main/java/com/maddyhome/idea/vim/extension/VimExtensionFacade.kt
src/main/java/com/maddyhome/idea/vim/extension/commentary/CommentaryExtension.kt
src/main/java/com/maddyhome/idea/vim/extension/exchange/VimExchangeExtension.kt
src/main/java/com/maddyhome/idea/vim/extension/replacewithregister/ReplaceWithRegister.kt
src/main/java/com/maddyhome/idea/vim/extension/surround/VimSurroundExtension.kt
src/main/java/com/maddyhome/idea/vim/group/IjOptionProperties.kt
src/main/java/com/maddyhome/idea/vim/group/IjOptions.kt
src/main/java/com/maddyhome/idea/vim/newapi/IjVimApplication.kt
src/test/java/org/jetbrains/plugins/ideavim/action/change/OperatorActionTest.kt
src/test/java/org/jetbrains/plugins/ideavim/ex/implementation/commands/SetCommandTest.kt
src/test/java/org/jetbrains/plugins/ideavim/ex/implementation/commands/SetglobalCommandTest.kt
src/test/java/org/jetbrains/plugins/ideavim/ex/implementation/commands/SetlocalCommandTest.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/api/OptionProperties.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/api/Options.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/api/VimApplication.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/api/VimKeyGroup.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/api/VimKeyGroupBase.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/api/stubs/VimApplicationStub.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/options/Option.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/vimscript/model/commands/SetCommand.kt

This PR introduces the `'operatorfunc'` option. This option contains the name of a function that can act like a custom operator, and is called by the `g@` command, such as in this example from the #702 discussion:
```vimL
nnoremap gx :set opfunc=Redact<cr>g@
function! Redact(type)
execute "normal `[v`]rx"
endfunction
```
Using a command such as `gxiw`, this map will invoke the custom operator function on a given word, and replace it with `x` characters.
The `'opfunc'` option can be the name of a function, a reference from `function('…')` or `funcref('…')` or a lambda.
This PR also allows an extension to export a script function that can be called from the VimScript executor, which is a simple wrapper function that invokes extension code. A helper function has been added to create a script …

Introduce 'operatorfunc' option for custom operators

---

src/main/java/com/maddyhome/idea/vim/helper/SearchHelper.java
src/main/java/com/maddyhome/idea/vim/newapi/IjVimSearchHelper.kt
src/main/java/com/maddyhome/idea/vim/package-info.java
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/action/motion/text/MotionMisspelledWord.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/api/VimSearchHelper.kt

Fixes part of https://youtrack.jetbrains.com/issue/VIM-330/Need-better-spell-checker-integration.
Implements `[s` and `]s` motions using IntelliJ's "Typo" inspection. Supports NVO modes, count, and multicursor, though I don't have spell checking in my `vim` so I'm not 100% sure if the behavior matches.

Implement motions to go to next/previous misspelled word

---

src/main/java/com/maddyhome/idea/vim/PluginStartup.kt
src/main/java/com/maddyhome/idea/vim/group/EditorGroup.java
src/main/java/com/maddyhome/idea/vim/group/KeyGroup.java
src/main/java/com/maddyhome/idea/vim/group/SearchGroup.java
src/main/java/com/maddyhome/idea/vim/group/VimJumpServiceImpl.kt
src/main/java/com/maddyhome/idea/vim/group/VimMarkServiceImpl.kt
src/main/java/com/maddyhome/idea/vim/helper/EditorHelper.java
src/main/java/com/maddyhome/idea/vim/helper/SearchHighlightsHelper.kt
src/main/java/com/maddyhome/idea/vim/helper/UserDataManager.kt
src/main/java/com/maddyhome/idea/vim/listener/VimListenerManager.kt
src/main/java/com/maddyhome/idea/vim/ui/ExOutputPanel.java
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/api/VimEditorGroup.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/api/VimMarkServiceBase.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/api/VimOptionGroupBase.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/impl/state/VimStateMachineImpl.kt

This PR ensures that IdeaVim only works with editors that have been initialised. This is important for various callbacks, such as notifications when setting editor options. 
For example, the `~/.ideavimrc` file is evaluated during startup, before other editors are initialised. It can set various option values which in turn notify all affected editors. If the IDE opens editors at startup, these editors would be notified of changes before they've been initialised. [VIM-3256](https://youtrack.jetbrains.com/issue/VIM-3256) is an example of an issue caused by this - the uninitialised editors are notified, and try to check local-to-buffer options. These local-to-buffer options haven't yet been initialised, but trying to get a value will create the storage map for them, without setting any …

Only notify option change to initialised editors

---

src/main/java/com/maddyhome/idea/vim/extension/nerdtree/NerdTree.kt

NERDTree uses 'I' to toggle hidden files ([source](https://github.com/preservim/nerdtree/blob/6acfc48d80f83b7c23c4e6f9faa93c3defdb150b/doc/NERDTree.txt#L286)), which I think maps nicely to excluded files in IntelliJ, so I added support for it.

Add NERDTree action to toggle excluded files

---

src/main/java/com/maddyhome/idea/vim/extension/textobjindent/VimIndentObject.java

Previously it ignored the first indent character, which caused errors with tabs. You wouldn't get any errors in behavior with spaces as you'd typically have 4 spaces at each indent level, so 1 in calculation doesn't make a difference.
Can be tested on following text. Easier with vii
```
first level selects all
{
second level with tab. will still select all before fix
{
third level with tab. Will select also the second level before fix
}
}
first level selects all
{
second level with spaces. Will work before fix
{
third level with spaces. will only select that line
}
}
```

Fix indent size calculation in "vin indent object" extention

---

doc/IdeaVim Plugins.md

When I added the `terryma/vim-multiple-cursors` plugin, I struggled at first to get it working since `Ctrl+n` is mapped to something else by default; `Ctrl+n` is the default key bind for `terryma/vim-multiple-cursors`
This adds documentation on re-mapping to trigger multiple cursors and which command to use.

Update docs for multiple-cursors plugin

---

src/main/java/com/maddyhome/idea/vim/group/OptionGroup.kt
src/test/java/org/jetbrains/plugins/ideavim/option/overrides/ScrollJumpOptionMapperTest.kt
src/test/java/org/jetbrains/plugins/ideavim/option/overrides/ScrollOffOptionMapperTest.kt

This PR fixes a glitch with scrolling when `'scrolloff'` is greater than 0. Previously, the mapping of the `'scrolloff'` Vim option to IntelliJ's "vertical scroll offset" setting would update the (local, per-editor) IntelliJ setting to the same value. IntelliJ would use this when performing its own scrolling. However, IntelliJ's scrolling calculation includes the virtual space at the bottom of the file. So typing `G` would place the last line at the bottom of the screen, but then any caret movement would trigger IntelliJ's scrolling and move the last line up to include scroll offset/virtual space.
This was more noticeable with a large scroll offset, such as `999`, intended to keep the caret in the centre of the screen. After typing `G` to put the last line at the bottom of the screen, …

Fix glitch with 'scrolloff' mapping at bottom of file

---

gradle.properties

This PR fixes the `verifyPlugin` Gradle task after migrating to v2 of the Gradle IntelliJ Plugin. It was broken due to disabling the `useBinaryReleases` build feature, which controls whether the referenced IDE is downloaded as a consumer binary release from the main CDN, or from Maven. The default is to use consumer binary releases, but the Plugin DevKit plugin wasn't able to download sources for these references during debugging, etc. The Plugin DevKit has now been updated, and supports downloading sources for binary releases in 2024.1.4 and the latest 242 EAP.
This PR also enables Gradle caching. Without this, Gradle appears to re-run the "extractor transformer" on each run, which seems to extract the IDE ready to be referenced. This means running tests can have additional overhead, up …

Fix `verifyPlugin` Gradle task

---

src/main/java/com/maddyhome/idea/vim/helper/SearchHighlightsHelper.kt
src/test/java/org/jetbrains/plugins/ideavim/group/SearchGroupTest.kt

If all results are before the caret, make sure it's still possible to find the closest match.
Fixes [VIM-3505](https://youtrack.jetbrains.com/issue/VIM-3505)

Fix incsearch with result before caret and wrapscan

---

src/main/java/com/maddyhome/idea/vim/ex/ExOutputModel.kt
src/main/java/com/maddyhome/idea/vim/group/EditorGroup.java
src/main/java/com/maddyhome/idea/vim/group/MotionGroup.kt
src/main/java/com/maddyhome/idea/vim/listener/VimListenerManager.kt
src/main/java/com/maddyhome/idea/vim/ui/ExOutputPanel.java

Fixes an exception that would prevent debugging in Rider. The Debug tool window would create an `Editor` instance during initialisation and set the font size. If the font size was changed (e.g. the editor was zoomed), then IdeaVim's font property change listener would try to hide the ex command line and the output panel. Unfortunately, this forced creation of the output panel, which would try to position itself, but because the `Editor` instance hadn't been added to the UI, the editor component's root pane would be null, and lead to a `NullPointerException`.
This PR adds a null check to avoid the exception, and also avoids creating the panel just to make sure it's hidden.
Fixes [VIM-3515](https://youtrack.jetbrains.com/issue/VIM-3515)

Fix null reference initialising output panel fonts

---

.github/workflows/closeYoutrackOnCommit.yml
.github/workflows/mergePr.yml
.github/workflows/updateAuthors.yml
.github/workflows/updateChangelog.yml
build.gradle.kts
gradle.properties
tests/long-running-tests/build.gradle.kts
tests/property-tests/build.gradle.kts
vim-engine/build.gradle.kts

This fixes an issue with the sandbox not being properly reset if the IDE is killed rather than gracefully exits. Updates to the current syntax for running tests.
Also disables the configuration cache for Gradle tasks in GitHub actions. The tasks should be updated to work with the cache, but in the meantime, this change should make them work again as actions.

Update IntelliJ Gradle plugin to beta 8

---

README.md
doc/marketplace-plugin-example.md
src/main/java/com/maddyhome/idea/vim/group/NotificationService.kt
src/main/java/com/maddyhome/idea/vim/listener/IdeaSpecifics.kt
src/main/resources/messages/IdeaVimBundle.properties

Some actions are registered with a local component, and not with `ActionManager`, for example `NextTab` has a different implementation for editor tabs and tool window tabs. This means we can't use the action instance to look up an action ID from `ActionManager`, and the "track action IDs" feature can't show the executed action ID.
However, the action is a copy of the global "template" action, including shortcuts. We can use the shortcuts to look up and display all possible action IDs as candidates. The notification might therefore include multiple actions, but it is likely to include the required action.
Fixes [VIM-3499](https://youtrack.jetbrains.com/issue/VIM-3499).

Show possible action IDs when tracking, based on current shortcut

---

src/test/java/org/jetbrains/plugins/ideavim/action/MotionActionTest.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/action/change/change/ChangeCharacterAction.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/action/change/change/ChangeVisualCharacterAction.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/action/change/insert/InsertCompletedDigraphAction.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/action/change/insert/InsertCompletedLiteralAction.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/action/ex/InsertRegisterAction.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/action/macro/ToggleRecordingAction.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/command/CommandBuilder.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/common/DigraphResult.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/common/DigraphSequence.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/handler/EditorActionHandlerBase.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/key/consumers/CommandConsumer.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/key/consumers/DigraphConsumer.kt

I've been looking at how extensions interact with `CommandBuilder` (spoiler: badly) and before fixing some of these extension related things, I've done some small refactorings in the following:
* Removing some unused functions + properties from `CommandBuilder`
* Removing some special case code in `CommandConsumer` that were based on action names
* Refactor `DigraphResult` implementation to use sealed classes
* Fixing some minor correctness issues with `CommandBuilder` not using the proper command part when trying to get the in-progress count or register
Pinging @lippfi as I know you're working with `CommandBuilder`. These changes should be more about implementation details than significant changes, so hopefully shouldn't cause conflicts.

Small refactorings around CommandBuilder

---

src/main/java/com/maddyhome/idea/vim/group/EditorGroup.java

Unlike other IDEs, Rider has multiple client sessions. The IDE itself is the "local" session, just like other IDEs, and each external ReSharper process is treated as a "frontend" process - one for each opened solution. The code to get local editors was erroneously getting `ALL` sessions, rather than just `LOCAL` sessions, and assuming that the first was the local session. In Rider, opening three instances would add three additional "frontend" clients, and this would change the order of the returned sessions, so the first instance was an arbitrary "frontend" session, rather than the expected "local" session. This meant IdeaVim was trying to retrieve the wrong list of editors to work with. The most obvious impact of this is that search highlights were not shown during incremental search, …

Fix 'incsearch' highlight in multiple Rider instances

---

src/main/java/com/maddyhome/idea/vim/helper/IjActionExecutor.kt
tests/java-tests/src/test/kotlin/org/jetbrains/plugins/ideavim/action/ChangeActionJavaTest.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/action/fold/FoldActions.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/api/VimActionExecutor.kt

Original request for `za` I could find [here](https://youtrack.jetbrains.com/issue/VIM-566/Support-more-Vim-folding-commands)
Personally, I wanted this so adding it.
`ExpandCollapseToggleAction` is not yet exposed in `IdeActions` I have a PR [here](https://github.com/JetBrains/intellij-community/pull/2825) to expose it.
It's up to the maintainers here if you'd prefer I wait till that's merged so I dont have a hard-coded string.
I was able to build intelliJ with this change and validated the toggling works as I expect it, feedback welcome!
Note: I dont really understand the `@TestWithoutNeovim(SkipNeovimReason.FOLDING)` so please direct me if I should remove it

VIM-566: Add za motion support for toggling folds

---

CHANGES.md

I wanted to see which fixes were included in the latest version, so I added a [version fixes](https://youtrack.jetbrains.com/issues/VIM?q=State:%20Fixed%20sort%20by:%20%7BFix%20versions%7D%20asc) link for that.  And I fixed the formatting so the links appear on their own line.

[changelog] add YouTrack link for version fixes

---

src/main/java/com/maddyhome/idea/vim/helper/SearchHighlightsHelper.kt
src/main/java/com/maddyhome/idea/vim/helper/UndoRedoHelper.kt
src/test/java/org/jetbrains/plugins/ideavim/action/change/UndoActionTest.kt
src/test/java/org/jetbrains/plugins/ideavim/ex/implementation/commands/RedoCommandTest.kt
src/test/java/org/jetbrains/plugins/ideavim/ex/implementation/commands/UndoCommandTest.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/action/change/RedoAction.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/action/change/UndoAction.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/vimscript/model/commands/RedoCommand.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/vimscript/model/commands/UndoCommand.kt

This PR fixes a couple of small bugs:
1. Highlighting for `'incsearch'` now only applies to editors in the current project, rather than all open projects - [VIM-3682](https://youtrack.jetbrains.com/issue/VIM-3682)
2. Fixes an issues where undo/redo does not move the caret when used in an editor with a preview, such as Markdown files, or all source files in Android Studio (which includes a preview based on the code). IdeaVim will also ensure that `'scrolloff'` is applied after undo/redo - [VIM-3671](https://youtrack.jetbrains.com/issue/VIM-3671)

Minor fixes for incsearch highlighting and caret/scroll position for undo

---

src/main/java/com/maddyhome/idea/vim/handler/VimEnterHandler.kt
src/main/resources/META-INF/plugin.xml

Before, the Inline Completion providers (like Full Line Code Completion and AI Assistant Completion) weren't triggered by an Enter hit. It fixes the problem.
Please note that `inline.completion.enter` handler will be available since the tomorrow build. But it looks like it doesn't create problems for the previous versions of IDE (the missing action handler).

[ai-completion] LLM-11886: make AI completion invoke on Enter when IdeaVim is turned on

---

build.gradle.kts
gradle.properties
src/main/java/com/maddyhome/idea/vim/extension/highlightedyank/VimHighlightedYank.kt
src/main/java/com/maddyhome/idea/vim/group/FileGroup.kt
src/main/java/com/maddyhome/idea/vim/group/VimMarkServiceImpl.kt
src/main/java/com/maddyhome/idea/vim/group/visual/VimVisualTimer.kt
src/main/java/com/maddyhome/idea/vim/helper/CaretVisualAttributesHelper.kt
src/main/java/com/maddyhome/idea/vim/helper/ScrollViewHelper.kt
src/main/java/com/maddyhome/idea/vim/helper/UserDataManager.kt
src/main/java/com/maddyhome/idea/vim/listener/VimListenerManager.kt
src/main/java/com/maddyhome/idea/vim/newapi/IjVimInjector.kt
src/main/java/com/maddyhome/idea/vim/newapi/IjVimSearchGroup.kt
src/main/java/com/maddyhome/idea/vim/ui/ex/ExEditorKit.kt
src/main/java/com/maddyhome/idea/vim/vimscript/model/commands/ActionListCommand.kt
src/main/java/com/maddyhome/idea/vim/vimscript/model/commands/CmdFilterCommand.kt
src/test/java/org/jetbrains/plugins/ideavim/ex/implementation/commands/PrintCommandTest.kt
src/test/java/org/jetbrains/plugins/ideavim/option/overrides/LineNumberOptionsMapperTest.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/action/change/change/ChangeCaseLowerMotionAction.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/action/change/change/ChangeCaseLowerVisualAction.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/action/change/change/ChangeCaseToggleVisualAction.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/action/change/change/ChangeCaseUpperMotionAction.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/action/change/change/ChangeCaseUpperVisualAction.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/action/change/insert/InsertBackspaceAction.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/api/VimScriptExecutorBase.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/common/VimListenersNotifier.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/helper/EngineHelper.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/regexp/engine/nfa/matcher/VisualAreaMatcher.kt

Updates the build target/minium version to 2024.2.1 (2024.2.0 is no longer available), fixes a deprecated API usage, and cleans up some unused imports.
I haven't made any changes to the usages of "2024.1" in the `.teamcity` folder.
It's also worth checking `IjActionExecutor`. There is a usage of the deprecated `AnAction.beforeActionPerformed` API that is marked as an error because it's scheduled for removal.

Update minimum version to 242

---

src/test/java/org/jetbrains/plugins/ideavim/helper/CaretVisualAttributesHelperTest.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/options/helpers/GuiCursorOptionHelper.kt

This PR will use the caret shape specified by `ve` in the `'guicursor'` option when Visual mode is active and the `'selection'` option equals `exclusive`. If the `ve` element isn't specified in `'guicursor'`, the `v` element is used instead.
This PR will also now use the `ve` element for Select mode. Previously, we were using the `i` Insert mode cursor (Vim doesn't have a separate Select cursor). This felt like a reasonable change at the time for several reasons. Firstly, Select mode is more similar to a traditional editor selection where typing inserts the text, replacing the selection, so using the Insert mode caret was an intuitive indicator of this. Secondly, when used in refactorings, the caret would be positioned after the selection, so a bar caret looks better.
However, the caret …

Small bug fix to use exclusive Visual caret shape from 'guicursor'

---

src/test/java/org/jetbrains/plugins/ideavim/action/scroll/ScrollPageDownActionTest.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/action/motion/scroll/MotionScrollPageDownAction.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/action/window/tabs/NextTabAction.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/action/window/tabs/PreviousTabAction.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/api/VimStringParserBase.kt
vim-engine/src/main/resources/ksp-generated/engine_commands.json

* Adds a map for `<C-PageUp/Down>` and `i_<C-PageUp/PageDown>` to switch tabs - [VIM-2044](https://youtrack.jetbrains.com/issue/VIM-2044)
* Adds a map for `<S-Enter>` to scroll page forward - [VIM-2752](https://youtrack.jetbrains.com/issue/VIM-2752)
* Removes some old extended handling of special keys that was required when keys for actions were registered via a comma separated string in an XML attribute. Removes recognising `«` and `»` and also `<Comma>`

Add some missing maps

---

src/main/java/com/maddyhome/idea/vim/listener/VimListenerManager.kt
src/test/java/org/jetbrains/plugins/ideavim/listener/VimListenersTest.kt

When an editor is initialised, IdeaVim registers various listeners and uses a new per-editor disposable to remove the registrations. When the IdeaVim plugin is disabled/unloaded by the platform, the parent disposable is disposed, and all listeners are unregistered. All per-editor disposables are also disposed when IdeaVim disables Vim functionality without disbaling the whole plugin. However, the per-editor disposable is not disposed at any other time, e.g., when the editor is closed. So IdeaVim is leaking disposables.
Since each registration's disposable needs to call an editor method to remove the listener, each disposable captures a reference to the editor. Because the disposables are not removed when an editor is closed, that means IdeaVim is leaking editor instances.
(Some listener …

Fix memory leak with non-disposed listeners

---

src/test/java/org/jetbrains/plugins/ideavim/ex/implementation/functions/GetCmdTypeFunctionTest.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/vimscript/model/functions/handlers/GetCmdTypeFunctionHandler.kt
vim-engine/src/main/resources/ksp-generated/engine_vimscript_functions.json

The `getcmdtype()` could be called from inside a prompt (search, expression, command), or from a remapping. Apparently IdeaVim currently doesn't support nested prompts (e.g. by typing `:<C-r>=` to show an expression prompt inside a command prompt), so it wouldn't be functional in that case.
It should work in a remapping though, e.g.: `:cnoremap <F2> <C-r>=getcmdtype()<CR>`. Could you advise on how I could unit test this?
For context, this is the remap that I'm using this for:
```
cnoremap <expr> <Esc> getcmdtype() =~ '[/?]' ? '<CR><Esc>' : '<Esc>'
```
This is so that if you press `<Escape>` during a search before you press enter, it keeps the cursor at the first search result instead of jumping back to where the cursor was before the search started. This enforces a behavior that you find …

Add partial support for getcmdtype() function

---

src/main/java/com/maddyhome/idea/vim/group/OptionGroup.kt
src/main/java/com/maddyhome/idea/vim/listener/VimListenerManager.kt
src/test/java/org/jetbrains/plugins/ideavim/option/OptionDeclaredScopeTest.kt
src/test/java/org/jetbrains/plugins/ideavim/option/overrides/WrapOptionMapperTest.kt
src/testFixtures/kotlin/org/jetbrains/plugins/ideavim/VimTestCase.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/api/VimOptionGroupBase.kt

This PR will fix options initialisation in 2024.2 and above.
Options are initialised based on the currently selected editor (Vim "window"). In 2024.1, we could use `FileEditorManager.selectedTextEditor` to get the last selected text editor while creating a new editor. This value can no longer be relied upon in 2024.2, as the value is reset to `null` when a new editor (that will become the next selected editor) is being created.
This meant we were always initialising window options based on the "fallback" window. Vim always has at least one window open, so there is always a window to initialise _from_. IntelliJ can close all windows, so we need to keep track of the options used by the window that was last to be closed - so if there are no open windows, we can initialise from the "fallback" …

Fix options initialisation in 2024.2+

---

src/test/java/org/jetbrains/plugins/ideavim/action/change/change/ChangeMotionActionTest.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/action/change/change/ChangeMotionAction.kt

Repeating the `c` command should not repeat inserting the text. This is mostly visible when the command is initially made with a count. E.g. `2c3l` will change 6 characters. Hitting `.` should also change 6 characters and shouldn't repeat inserting the text 6 times.
This PR adds `CommandFlags.FLAG_NO_REPEAT_INSERT`, as used by `s`, `S` and `C`.
Fixes [VIM-3729](https://youtrack.jetbrains.com/issue/VIM-3729)

Fix repeating change action with count

---

src/test/java/org/jetbrains/plugins/ideavim/action/change/insert/InsertEnterActionTest.kt
src/test/java/org/jetbrains/plugins/ideavim/action/motion/select/SelectEnterActionTest.kt
src/test/java/org/jetbrains/plugins/ideavim/action/motion/updown/MotionDownActionTest.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/action/change/insert/InsertEnterAction.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/action/motion/select/SelectEnterAction.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/action/motion/updown/MotionDownActions.kt
vim-engine/src/main/resources/ksp-generated/engine_commands.json

Adds `<C-J>` support in Normal, Insert, Visual, Select and Operator-pending. Also adds support for `<C-M>` in Select.
Fixes [VIM-3740](https://youtrack.jetbrains.com/issue/VIM-3740)

Add support for CTRL-J

---

src/main/java/com/maddyhome/idea/vim/group/KeyGroup.java
src/main/java/com/maddyhome/idea/vim/helper/ModeExtensions.kt
src/test/java/org/jetbrains/plugins/ideavim/action/motion/select/SelectDeleteActionTest.kt
src/test/java/org/jetbrains/plugins/ideavim/action/motion/select/SelectEscapeActionTest.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/action/motion/select/SelectDeleteAction.kt
vim-engine/src/main/resources/ksp-generated/engine_commands.json

This PR fixes an issue when hitting `<Del>` or `<BS>` to delete selected text in Select mode would fail to delete anything. The implementation would try to invoke native actions to delete but had two problems. Firstly, it would fail to filter out the IdeaVim action bound to the keystroke and would recurse (but fail to invoke anything). Secondly, it would also try to invoke instances of `EmptyAction`, which are placeholder actions that are used to reserve a shortcut. Code will use look for these actions by ID to look up the shortcut to use when dynamically registering the real action locally in a `Component`. We gather these locally registered actions, so it's safe to ignore the empty action.
It also correctly transitions from Select mode to Normal or Insert/Replace, depending on context. …

Fix Del and BS not working in Select mode

---

src/main/java/com/maddyhome/idea/vim/listener/IJEditorFocusListener.kt

When an editable console editor gets focus, IdeaVim automatically enters Insert mode. However, we can't always tell a console editor window is editable when it gains focus, so we do an additional check via `application.invokeLater`. If this switches to Insert mode, it doesn't correctly reset the (newly focused console) editor, so even though the mode is "Insert", it was last reset with "Normal". This PR will reset the editor state (including key handler) so that the new mode is "applied".
Fixes [VIM-3773](https://youtrack.jetbrains.com/issue/VIM-3773)

Fix race condition resetting editor on focus gain

---

src/test/java/org/jetbrains/plugins/ideavim/action/MarkTest.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/action/motion/mark/MotionGotoMarkAction.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/api/VimMarkService.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/api/VimMarkServiceBase.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/api/VimMotionGroup.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/api/VimMotionGroupBase.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/mark/Marks.kt
vim-engine/src/main/resources/ksp-generated/engine_commands.json

Fixes [VIM-3731](https://youtrack.jetbrains.com/issue/VIM-3731/Add-support-for-jump-to-previous-next-lowercase-mark).
Let me know if I should do anything else with `Mark.PositionSorter`.  The two data structures are in different packages, so I wasn't sure if sharing the code would be desired or where you'd want the shared code to live.

[VIM-3731] Add support for "jump to previous/next lowercase mark".

---

doc/IdeaVim Plugins.md
src/main/java/com/maddyhome/idea/vim/extension/miniai/MiniAI.kt
src/main/java/com/maddyhome/idea/vim/statistic/PluginState.kt
src/main/resources/META-INF/includes/VimExtensions.xml
src/test/java/org/jetbrains/plugins/ideavim/ex/implementation/commands/SetCommandTest.kt
src/test/java/org/jetbrains/plugins/ideavim/ex/implementation/commands/SetglobalCommandTest.kt
src/test/java/org/jetbrains/plugins/ideavim/ex/implementation/commands/SetlocalCommandTest.kt
tests/java-tests/src/test/kotlin/org/jetbrains/plugins/ideavim/extension/miniai/MiniAIExtensionTest.kt

This PR introduces the mini-ai extension to the IdeaVim project, which provides additional text object motions for handling quotes and brackets. The following motions are included:
- `aq`: Around any quotes.
- `iq`: Inside any quotes.
- `ab`: Around any parentheses, curly braces, and square brackets.
- `ib`: Inside any parentheses, curly braces, and square brackets.
The extension enhances the text object capabilities of IdeaVim, allowing for more flexible text manipulation.
- Created a new extension class `MiniAI` that registers the text object motions.
- Implemented handlers for both inner and outer text objects for quotes and brackets.
- Added utility functions for calculating distances to improve selection accuracy.
Please review the changes and let me know if any modifications are …

feat: add mini-ai extension to support motions like aq, iq, ab and ib

---

src/main/java/com/maddyhome/idea/vim/extension/miniai/MiniAI.kt
src/test/java/org/jetbrains/plugins/ideavim/extension/miniai/MiniAIExtensionTest.kt
tests/java-tests/src/test/kotlin/org/jetbrains/plugins/ideavim/extension/miniai/MiniAIExtensionTest.kt

The mini.ai extension had an issue with nested quotes or brackets selection.
When dealing with nested quotes, the extension should select the innermost quotes containing the cursor. However, it was incorrectly selecting outer quotes due to the distance calculation logic.
current state: This is a "simple '|example'" that works
After pressing ciq it should produce the following result:
expected: This is a "simple '|'" that works
However it is behaving like this:
actual: This is a "|" that works
The distanceTo function has been refactored to prioritize:
- Ranges that contain the cursor
- Smaller ranges over larger ones
- Heavily penalize ranges where the cursor is outside
I noticed that the distanceTo function was wrong, this pr fixes it.
Please take a look at the new tests to understand the …

fix: distanceTo to works with nested quotes and brackets (mini.ai) plugin

---

src/main/java/com/maddyhome/idea/vim/extension/miniai/MiniAI.kt
src/test/java/org/jetbrains/plugins/ideavim/extension/miniai/MiniAIExtensionTest.kt

This PR modifies the mini.ai‐like text object logic to prioritize brackets or quotes on the same line as the caret before considering the rest of the buffer. It addresses scenarios like the unit test `testNextBracketInCurrentLineHasPriority`, where the user expects “next bracket on the same line” to be chosen over a larger multi‐line bracket pair.
1. Two‐pass approach for finding text objects:
- First pass: Gather and choose from bracket/quote pairs that occur on the caret’s line (using the same mini.ai “cover‐or‐next” logic).
- Second pass: If no suitable text object is found on that line, we then gather pairs from the entire buffer and pick again with the “cover‐or‐next” approach.
2. Inner vs. Outer handling remains the same:
- If the user requests an “inner” text object (e.g., ib or …

feat: improve mini.ai extension behavior to be exactly as the original plugin for complex scenarios.

---

src/test/java/org/jetbrains/plugins/ideavim/action/motion/select/motion/SelectMotionBigWordLeftActionTest.kt
src/test/java/org/jetbrains/plugins/ideavim/action/motion/select/motion/SelectMotionBigWordRightActionTest.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/action/motion/select/motion/SelectMotionBigWordLeftAction.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/action/motion/select/motion/SelectMotionBigWordRightAction.kt
vim-engine/src/main/resources/ksp-generated/engine_commands.json

This PR adds `<C-Left>` and `<C-Right>` actions in Select mode to move to the previous/next WORD. It adds new actions, similar to the existing actions for `<C-Left>` and `<C-Right>` for Visual mode. They're separate actions because the Visual mode actions are also mapped to the `B` shortcut, which isn't valid for Select.
Note that the tests don't all follow Vim behaviour. Firstly, there is a separate bug/mis-implementation that entering select with e.g. `gh` will move the caret one character to the right in IdeaVim, but not in Vim. This will be addressed in a separate PR that does a bunch of work around Select mode, inclusive/exclusive selection, off-by-one errors and so on. Secondly, IdeaVim treats Select mode as always being "exclusive", as if `:set selection=exclusive` has been called. …

Add missing shortcuts for WORD left/right in Select

---

src/test/java/org/jetbrains/plugins/ideavim/ex/implementation/commands/MoveCommandTest.kt
src/test/java/org/jetbrains/plugins/ideavim/ex/implementation/functions/cursorFunctions/ColFunctionTest.kt
src/test/java/org/jetbrains/plugins/ideavim/ex/implementation/functions/cursorFunctions/LineFunctionTest.kt
src/testFixtures/kotlin/org/jetbrains/plugins/ideavim/VimTestCase.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/KeyHandler.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/vimscript/model/commands/MoveTextCommand.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/vimscript/model/functions/handlers/cursorFunctions/ColLineFunctionHandler.kt

Fixes the caret location after the `:move` command, especially with regard to relative addresses, such as `:+2m.`. Fixes [VIM-3837](https://youtrack.jetbrains.com/issue/VIM-3837).
Also makes some minor changes to clarify some behaviour that appeared related but wasn't. Namely, that `line('v')` returns the opposite end of the current selection (related to [VIM-3838](https://youtrack.jetbrains.com/issue/VIM-3838))

Fix caret location after :move command

---

src/main/java/com/maddyhome/idea/vim/extension/surround/VimSurroundExtension.kt
src/test/java/org/jetbrains/plugins/ideavim/extension/surround/VimSurroundExtensionTest.kt

Fixes [VIM-3841](https://youtrack.jetbrains.com/issue/VIM-3841/Unhandled-key-press-after-surround-operation).
Given a command such as `veS"`, IdeaVim will enter Visual mode, surround the selection with `"` and exit Visual. A subsequent keystroke such as `i` has no effect.
This is because the key handler is not reset when leaving Visual mode, and continues to try and process keystrokes as Visual. This PR resets the key handler.
See discussion at #1124.

Fix unhandled key stroke after surround operation

---

README.md
doc/IdeaVim Plugins.md

When I was first getting my IdeaVim setup it was hard to know what each plugin did on the `IdeaVim Plugins` page without going to every link and reading through the repos. 
I added small inline summaries to each title (like what Mini.ai already had), and added a larger summary to each plugins details. 
I also made both the plugin list on the main README, and in the IdeaVim Plugins.md alphabetical.

Reorder and add information to plugins doc.

---

src/main/java/com/maddyhome/idea/vim/group/ChangeGroup.kt
src/main/java/com/maddyhome/idea/vim/newapi/IjVimApplication.kt
src/test/java/org/jetbrains/plugins/ideavim/ex/implementation/commands/MapCommandTest.kt
src/test/java/org/jetbrains/plugins/ideavim/ex/implementation/commands/NormalCommandTest.kt
src/test/java/org/jetbrains/plugins/ideavim/ui/ShowCmdTest.kt
src/testFixtures/kotlin/org/jetbrains/plugins/ideavim/VimTestCase.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/KeyHandler.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/api/VimApplication.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/api/VimChangeGroup.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/api/VimChangeGroupBase.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/api/stubs/VimApplicationStub.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/command/MappingProcessor.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/key/KeyConsumer.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/key/KeyMapping.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/key/MappingInfo.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/key/consumers/CharArgumentConsumer.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/key/consumers/CommandConsumer.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/key/consumers/CommandCountConsumer.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/key/consumers/DeleteCommandConsumer.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/key/consumers/DigraphConsumer.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/key/consumers/EditorResetConsumer.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/key/consumers/ModalInputConsumer.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/key/consumers/ModeInputConsumer.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/key/consumers/RegisterConsumer.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/key/consumers/SelectRegisterConsumer.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/vimscript/model/commands/ActionCommand.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/vimscript/model/commands/Command.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/vimscript/model/commands/NormalCommand.kt

This PR refactors `MappingProcessor`, primarily to remove the need for the `mappingComplete` parameter, which is required for a forthcoming PR. However, a bigger impact is on the way unhandled keys are processed after a mapping fails.
With regard to the `mappingComplete` parameter, this has been removed from `KeyConsumer`, but not from `KeyHandler.handleKey`. This function is used by external plugins, so will need to remain. It hasn't been marked as deprecated because there isn't an alternative yet. That will be taken care of in a forthcoming PR.

Refactor mapping to better handle replaying failed mappings

---

src/main/java/com/maddyhome/idea/vim/group/IjOptionProperties.kt
src/main/java/com/maddyhome/idea/vim/group/IjOptions.kt

Removes the `'commandormotionannotation'` and `'vimscriptfunctionannotation'` internal options that were used as feature flags, but there's no longer a switch on behaviour.

Remove obsolete internal options

---

src/test/java/org/jetbrains/plugins/ideavim/extension/replacewithregister/ReplaceWithRegisterTest.kt

Link to YouTrack issue: [VIM-2263](https://youtrack.jetbrains.com/issue/VIM-2263)
In this PR I have added new tests that verify that content of the register referenced in **[count]["x]grr** and **["x]gr$** is used.

VIM-2263 "ReplaceWithRegister" plugin

---

src/test/java/org/jetbrains/plugins/ideavim/ex/implementation/expressions/datatypes/VimFloatTest.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/vimscript/model/datatypes/VimFloat.kt

[VIM-3894](https://youtrack.jetbrains.com/issue/VIM-3894/Unit-tests-fail-on-host-with-German-locale)

Always print float numbers using period as a decimal separator, VIM-3894

---

src/test/java/org/jetbrains/plugins/ideavim/ex/implementation/commands/SubstituteCommandTest.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/regexp/VimRegex.kt

Fixes
* [VIM-3510](https://youtrack.jetbrains.com/issue/VIM-3510) IdeaVim fails switching case within backreferences,
* [VIM-3895](https://youtrack.jetbrains.com/issue/VIM-3895) Missing backreference should be substituted by empty string.

Replacement string fixes

---

src/main/java/com/maddyhome/idea/vim/helper/EditorHelper.java
src/main/java/com/maddyhome/idea/vim/helper/EditorHelper.kt
src/main/java/com/maddyhome/idea/vim/listener/IJEditorFocusListener.kt

Fixes [VIM-1217](https://youtrack.jetbrains.com/issue/VIM-1217/Enable-for-Code-Fragments-Webstorm). This ticket was to enable IdeaVim in injected code fragments. This already worked, but the fragment editor started in Insert mode because IdeaVim would see it as an editor that was not backed by a real file. With this change, IdeaVim will check if the fragment editor's virtual file is an injected code fragment file, backed with a real file.

Stop switching fragment editors to Insert mode

---

src/main/java/com/maddyhome/idea/vim/group/NotificationService.kt
src/main/java/com/maddyhome/idea/vim/listener/IdeaSpecifics.kt

If an alt+enter intention is invoked from Search Everywhere, IdeaVim's Track Action ID shows "Cannot detect action ID" instead of explaining that there is no action ID.
Relates to [VIM-2541](https://youtrack.jetbrains.com/issue/VIM-2541).

Report cannot track intention action

---

src/main/java/com/maddyhome/idea/vim/vimscript/model/functions/handlers/PopupMenuVisibleFunctionHandler.kt
src/main/resources/ksp-generated/intellij_vimscript_functions.json

Adds the [pumvisible()](https://vimdoc.sourceforge.net/htmldoc/eval.html#pumvisible\(\)) function that returns whether a code completion popup is visible. It allows, for example:
```
sethandler <A-J> a:vim
sethandler <A-K> a:vim
" Use A-J/K to navigate code completion popups, or clone carets in the editor
map <expr> <A-j> pumvisible() ? '<Action>(EditorDown)' : '<Action>(EditorCloneCaretBelow)'
map <expr> <A-k> pumvisible() ? '<Action>(EditorUp)' : '<Action>(EditorCloneCaretAbove)'
imap <expr> <A-j> pumvisible() ? '<Action>(EditorDown)' : '<Action>(EditorCloneCaretBelow)'
imap <expr> <A-k> pumvisible() ? '<Action>(EditorUp)' : '<Action>(EditorCloneCaretAbove)'
" When pressing '&', accept selected suggestion and follow it with '&&'
imap <expr> & pumvisible() ? …
```

Implement pumvisible() function

---

src/test/java/org/jetbrains/plugins/ideavim/ex/implementation/commands/RegistersCommandTest.kt
src/test/java/org/jetbrains/plugins/ideavim/register/RegisterMacroTest.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/register/Register.kt

This PR fixes https://youtrack.jetbrains.com/issue/VIM-3819/Arrow-keys-in-macros-are-broken that was caused when the `Register` that was refactored to be immutable in f1f86b5c .
It makes the register based on `KeyStroke` instead of the copied text.

Fix VIM-3819 Arrow keys in macros are broken

---

src/test/java/org/jetbrains/plugins/ideavim/action/change/change/ChangeCaseToggleCharacterActionTest.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/action/change/change/ChangeCaseLowerMotionAction.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/action/change/change/ChangeCaseToggleMotionAction.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/action/change/change/ChangeCaseUpperMotionAction.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/api/VimChangeGroup.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/api/VimChangeGroupBase.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/api/VimMotionGroupBase.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/command/Argument.kt

We observed that the start of the range is the leftmost non-whitespace character OR the current position, whichever is closer to the left.

Fix(VIM-2413): correct the range of line-wise case change commands

---

vim-engine/src/main/kotlin/com/maddyhome/idea/vim/action/file/FileCloseAction.kt
vim-engine/src/main/resources/ksp-generated/engine_commands.json

ZQ is defined to `Quit without checking for changes (same as ":q!").`

Fix(VIM-2375): do not save file with `ZQ`

---

src/main/java/com/maddyhome/idea/vim/group/visual/IdeaSelectionControl.kt
src/main/java/com/maddyhome/idea/vim/listener/IJEditorFocusListener.kt
src/main/java/com/maddyhome/idea/vim/listener/IdeaSpecifics.kt
src/test/java/org/jetbrains/plugins/ideavim/action/change/insert/VisualInsertActionTest.kt
tests/java-tests/src/test/kotlin/org/jetbrains/plugins/ideavim/action/change/insert/VisualInsertActionJavaTest.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/action/change/insert/InsertAfterCursorAction.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/action/change/insert/InsertAtPreviousInsertAction.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/action/change/insert/InsertBeforeCursorAction.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/action/change/insert/VisualInsertAction.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/action/motion/select/motion/SelectMotionArrowLeftAction.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/action/motion/select/motion/SelectMotionArrowRightAction.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/api/VimChangeGroup.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/api/VimChangeGroupBase.kt
vim-engine/src/main/resources/ksp-generated/engine_commands.json

The bahavior seems undocumented. Based on my observation in Vim:
- For visual selections spanning multiple lines, keep caret position if it's on the first line.
- Otherwise move the caret to the start of the first selected line.

Fix(VIM-3044): correct the behavior of `I` in (linewise) Visual mode

---

src/test/java/org/jetbrains/plugins/ideavim/ex/implementation/commands/MarkCommandTest.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/vimscript/parser/visitors/CommandVisitor.kt

Vim allows `:k{mark}` to set a mark without requiring whitespace between the command `k` and the mark. While IdeaVim supports optional whitespace between a command and its argument, the catch-all "other" parser rule is greedier than the "command with comment" rule, and something like `:ka` is matched as an "other" command. This PR adds special handling for this case.
Fixes [VIM-3915](https://youtrack.jetbrains.com/issue/VIM-3915/k-shorter-mark-is-missing)

Handle `:k{mark}` without separating whitespace

---

src/main/java/com/maddyhome/idea/vim/extension/nerdtree/AbstractDispatcher.kt

Make the user aware by invoking `VimMessages.indicateError` to beep when an unrecognized key sequence is entered in NERDTree.

Indicate error when an unrecognized key sequence is entered in NERDTree

---

src/main/java/com/maddyhome/idea/vim/action/VimShortcutKeyAction.kt
src/main/java/com/maddyhome/idea/vim/action/editor/VimEditorActions.kt
src/main/java/com/maddyhome/idea/vim/helper/CaretVisualAttributesHelper.kt
src/main/java/com/maddyhome/idea/vim/helper/IjActionExecutor.kt
src/main/java/com/maddyhome/idea/vim/key/VimActionsPromoter.kt
src/test/java/org/jetbrains/plugins/ideavim/ex/implementation/commands/MapCommandTest.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/api/VimChangeGroupBase.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/command/CommandBuilder.kt
vim-engine/src/main/kotlin/com/maddyhome/idea/vim/key/consumers/EditorResetConsumer.kt

This PR fixes a number of compatibility issues with Next Edit Suggestions (AI generated related edits) - see [VIM-4010](https://youtrack.jetbrains.com/issue/VIM-4010). Specifically, `Tab` is now supported in Normal mode to review and accept the suggestions and the purple caret colour used to indicate a suggestion is available is maintained when IdeaVim changes mode. (The NES implementation has some issues with maintaining the current caret shape and overwriting the last shape when resetting - see [LLM-19241](https://youtrack.jetbrains.com/issue/LLM-19241/Maintain-custom-caret-shapes-IdeaVim))
In more detail: this PR changes the way `Tab` is handled in the IdeaVim pipeline. `Tab` is very similar to `Escape` and `Enter` in that it can have multiple contextual actions. E.g. `Escape` can …

Improve compatibility with Next Edit Suggestions

---

src/main/java/com/maddyhome/idea/vim/extension/nerdtree/AbstractDispatcher.kt
src/main/java/com/maddyhome/idea/vim/extension/nerdtree/Mappings.kt
src/main/java/com/maddyhome/idea/vim/extension/nerdtree/NerdTree.kt

- Initiate SpeedSearch right after <kbd>/</kbd> is pressed in NERDTree
- Clear NERDTree's KeyStroke buffer after <kbd>&lt;ESC&gt;</kbd> is pressed
- [VIM-3981](https://youtrack.jetbrains.com/issue/VIM-3981) make `:set noNERDTree` work
- Improve the concurrency of NERDTree mapping registration/disposal lifecycle
- Correct the behavior of <kbd>P</kbd> (`NERDTreeMapJumpRoot`) to jump to the root node

Improve SpeedSearch and disposal of NERDTree

---

src/main/resources/META-INF/plugin.xml

The `ProjectViewListener` has already been removed in 175bae51

Remove unused NerdTree `ProjectViewListener` from plugin.xml

---

.github/workflows/updateChangelogClaude.yml

- `.github/workflows/updateFormatting.yml` uses a safeguard `if: github.repository == 'JetBrains/ideavim'`, so scheduled runs are skipped on forks.
- `.github/workflows/updateChangelogClaude.yml` lacks the same check, so on forks the scheduled run fails due to missing secrets and sends daily alerts.
- Apply the same repository guard to `updateChangelogClaude` to stop failure notifications for all fork users (myself included).
- Fork users receive daily workflow failure alerts.
- Wastes CI resources and creates notification noise for forks.
Add the repository condition to `jobs.build` in `updateChangelogClaude`:
```yaml
jobs:
build:
runs-on: ubuntu-latest
if: github.repository == 'JetBrains/ideavim'
```
This pattern can be applied to other scheduled workflows if needed.

Prevent daily failure alerts from forks for Update Changelog workflow
