JetBrains/ideavim

test/org/jetbrains/plugins/ideavim/VimTestCase.java, test/org/jetbrains/plugins/ideavim/action/ChangeActionTest.java, test/org/jetbrains/plugins/ideavim/action/ChangeNumberActionTest.java, test/org/jetbrains/plugins/ideavim/action/MarkTest.java, test/org/jetbrains/plugins/ideavim/action/MotionActionTest.java, test/org/jetbrains/plugins/ideavim/action/ShiftRightLinesActionTest.java, test/org/jetbrains/plugins/ideavim/ex/RangeTest.java
Add some unit tests to increase test coverage.
=> Add some unit tests

src/com/maddyhome/idea/vim/action/motion/tabs/MotionNextTabAction.java, src/com/maddyhome/idea/vim/action/motion/tabs/MotionPreviousTabAction.java, src/com/maddyhome/idea/vim/group/MotionGroup.java
Implements https://youtrack.jetbrains.com/issue/VIM-868
'{count}gt' can now be used to switch to a specific tab.
=> VIM-868 Allow count on 'gt'

build.xml
Here's a couple of small improvements to `build.xml` I've found useful.
=> build.xml improvements

README.md
I stumbled around a bit adding my key mapping because I had forgotten that my .ideavimrc had been relocated.  Hopefully this note will help others in a similar situation.
=> Added note about where .ideavimrc is located

README.md
A small addition to README.md with deployment instructions.
=> Added deployment instructions to README.md

src/com/maddyhome/idea/vim/ex/handler/ActionHandler.java
also fixes VIM-1001, VIM-1016 and hopefully VIM-962 but unable to fully reproduce
=> VIM-892 Fix focus issues when executing :action commands from a keymap

src/com/maddyhome/idea/vim/extension/surround/VimSurroundExtension.java, test/org/jetbrains/plugins/ideavim/extension/surround/VimSurroundExtensionTest.java
=> Fix calculation of how to paste surrounded value

src/com/maddyhome/idea/vim/helper/PsiHelper.java, test/org/jetbrains/plugins/ideavim/action/MotionActionTest.java
=> Fix for VIM-965 with a test

src/com/maddyhome/idea/vim/group/ChangeGroup.java, test/org/jetbrains/plugins/ideavim/action/ChangeActionTest.java
Bug was introduced while fixing VIM-200
=> VIM-1380 Fixed 'cNw' at the last character of a word

src/com/maddyhome/idea/vim/group/FileGroup.java
https://youtrack.jetbrains.com/issue/VIM-1404
=> Fixes #VIM-1404.

src/com/maddyhome/idea/vim/ex/CommandParser.java, src/com/maddyhome/idea/vim/ex/handler/ShellHandler.java
`:shell` to activate terminal window.
=> added :shell command

src/com/maddyhome/idea/vim/ui/ExEntryPanel.java, src/com/maddyhome/idea/vim/ui/ExOutputPanel.java, src/com/maddyhome/idea/vim/ui/ExTextField.java
Causes the command bar and the output panel to redraw with the correct theme colours when the look and feel is changed.
Fixes [VIM-1303](https://youtrack.jetbrains.com/issue/VIM-1303)
=> VIM-1303 Update UI when look and feel changes

src/com/maddyhome/idea/vim/RegisterActions.java
Added keypad arrows supporting for VimMotions
=> VIM-944 - Navigation with keypad arrows 

resources/META-INF/plugin.xml, src/com/maddyhome/idea/vim/action/change/change/number/ChangeNumberDecAction.java, src/com/maddyhome/idea/vim/action/change/change/number/ChangeNumberIncAction.java, src/com/maddyhome/idea/vim/action/change/change/number/ChangeVisualNumberAvalancheDecAction.java, src/com/maddyhome/idea/vim/action/change/change/number/ChangeVisualNumberAvalancheIncAction.java, src/com/maddyhome/idea/vim/action/change/change/number/ChangeVisualNumberDecAction.java, src/com/maddyhome/idea/vim/action/change/change/number/ChangeVisualNumberIncAction.java, src/com/maddyhome/idea/vim/group/ChangeGroup.java, src/com/maddyhome/idea/vim/helper/SearchHelper.java, src/com/maddyhome/idea/vim/package-info.java, test/org/jetbrains/plugins/ideavim/action/change/change/number/ChangeVisualNumberAvalancheDecActionTest.kt, test/org/jetbrains/plugins/ideavim/action/change/change/number/ChangeVisualNumberAvalancheIncActionTest.kt, test/org/jetbrains/plugins/ideavim/action/change/change/number/ChangeVisualNumberDecActionTest.kt, test/org/jetbrains/plugins/ideavim/action/change/change/number/ChangeVisualNumberIncActionTest.kt
Add support for following commands:
- v_CTRL-A
- v_CTRL-X
- v_gCTRL-A
- v_gCTRL-X
---
It looks like `ChangeGroup.java` and `SearchHelper.java` contain a lot of changes, but they don't. This is just a refactoring to extract common parts for increment and decrement numbers in normal and visual modes.
=> VIM-1570 Support some increment and decrement commands

src/com/maddyhome/idea/vim/group/FileGroup.java
Hello friends!
This PR fixes [VIM-1012](https://youtrack.jetbrains.com/issue/VIM-1012)
The issue is that when you use `:q` or `:wq` or any other variants, ideavim will always focus the tab to the right unless it is the final tab in the group.  It should be honoring the intellij preference that allows you to configure focusing the left, right, or most recently used editor.
The `closeFile` method has protections in place in order to not close all of the tabs of the same file.  However, this implementation naively increments the focused tab index and moves on.  The intellij file editor api has an implementation that basically duplicates most of ideavim's `closeFile()` method while also honoring the directional preferences.  You can see that method …
=> [VIM-1012] Support tab close preferences when using :q or :wq

src/com/maddyhome/idea/vim/group/MotionGroup.java, test/org/jetbrains/plugins/ideavim/action/RepeatActionTest.kt
It solves https://youtrack.jetbrains.com/issue/VIM-1644
and related https://youtrack.jetbrains.com/issue/VIM-713 ! :tada: 
____
This pull request has been developed during [Open Source Saturday #24](https://www.meetup.com/it-IT/Open-Source-Saturday-Milano/events/260547473/) meetup in Milan.
=> [Vim 1644] - Fix action repeat broken with visual mode

src/com/maddyhome/idea/vim/action/window/WindowDownAction.java, src/com/maddyhome/idea/vim/action/window/WindowLeftAction.java, src/com/maddyhome/idea/vim/action/window/WindowRightAction.java, src/com/maddyhome/idea/vim/action/window/WindowUpAction.java, src/com/maddyhome/idea/vim/package-info.java
from vim help:
tag		command		   action in Normal mode
---------------------------------------------------------
|CTRL-W_CTRL-H|	CTRL-W CTRL-H	   same as "CTRL-W h"
|CTRL-W_CTRL-J|	CTRL-W CTRL-J	   same as "CTRL-W j"
|CTRL-W_CTRL-K|	CTRL-W CTRL-K	   same as "CTRL-W k"
|CTRL-W_CTRL-L|	CTRL-W CTRL-L	   same as "CTRL-W l"
=> map "<C-W><C-{H,J,K,L}>" to Window<Direction>Action

doc/set-commands.md, src/com/maddyhome/idea/vim/action/copy/PutTextAfterCursorAction.java, src/com/maddyhome/idea/vim/action/copy/PutTextAfterCursorActionMoveCursor.java, src/com/maddyhome/idea/vim/action/copy/PutTextAfterCursorNoIndentAction.java, src/com/maddyhome/idea/vim/action/copy/PutTextBeforeCursorAction.java, src/com/maddyhome/idea/vim/action/copy/PutTextBeforeCursorActionMoveCursor.java, src/com/maddyhome/idea/vim/action/copy/PutTextBeforeCursorNoIndentAction.java, src/com/maddyhome/idea/vim/action/copy/PutVisualTextAction.kt, src/com/maddyhome/idea/vim/action/copy/PutVisualTextMoveCursorAction.kt, src/com/maddyhome/idea/vim/action/copy/PutVisualTextNoIndentAction.kt, src/com/maddyhome/idea/vim/common/Register.java, src/com/maddyhome/idea/vim/ex/handler/CopyTextHandler.kt, src/com/maddyhome/idea/vim/ex/handler/MoveTextHandler.kt, src/com/maddyhome/idea/vim/ex/handler/PutLinesHandler.kt, src/com/maddyhome/idea/vim/extension/surround/VimSurroundExtension.java, src/com/maddyhome/idea/vim/group/RegisterGroup.java, src/com/maddyhome/idea/vim/group/copy/PutGroup.kt, src/com/maddyhome/idea/vim/option/Options.java, src/com/maddyhome/idea/vim/ui/ClipboardHandler.java, test/org/jetbrains/plugins/ideavim/action/MultipleCaretsTest.java, test/org/jetbrains/plugins/ideavim/action/copy/PutTextAfterCursorActionTest.kt, test/org/jetbrains/plugins/ideavim/action/copy/PutVisualTextMoveCursorActionTest.kt, test/org/jetbrains/plugins/ideavim/ex/MultipleCaretsTest.kt
[VIM-25](https://youtrack.jetbrains.com/issue/VIM-25) VIM code paste should be smarter
=> VIM-25 Smart put operations (via IJ)

CHANGES.md, src/com/maddyhome/idea/vim/ui/ExTextField.java
Fixes [VIM-1766](https://youtrack.jetbrains.com/issue/VIM-1766).
=> [VIM-1766] Fix ex caret rendering on Linux

src/com/maddyhome/idea/vim/ex/vimscript/VimScriptParser.java
This pull request solves [VIM-664](https://youtrack.jetbrains.com/issue/VIM-664). If `ideavimrc` file exist in XDG config directory use it instead the one in home dir. Works according to [XDG spec](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html), that is it uses directory specified in `XDG_CONFIG_HOME` environment variable if set and `~/.config` otherwise.
Any feedback appreciated.
=> VIM-664 - read ideavimrc from XDG config home directory

src/com/maddyhome/idea/vim/package-info.java, src/com/maddyhome/idea/vim/ui/ExKeyBindings.kt
I implemented CTRL-N and CTRL-P in the command mode.
=> Implement c_CTRL-N/P

src/com/maddyhome/idea/vim/helper/SearchHelper.java, src/com/maddyhome/idea/vim/helper/SearchHelperKt.kt, test/org/jetbrains/plugins/ideavim/action/MotionActionTest.java, test/org/jetbrains/plugins/ideavim/action/motion/object/MotionInnerBlockParenActionTest.kt, test/org/jetbrains/plugins/ideavim/helper/SearchHelperTest.java
Finally make it to pass all tests
=> Fix block actions (i.e ci{) in presence of quotes (VIM-1008)

resources/META-INF/includes/VimExtensions.xml, src/com/maddyhome/idea/vim/extension/VimExtensionFacade.kt, src/com/maddyhome/idea/vim/extension/exchange/VimExchangeExtension.kt, src/com/maddyhome/idea/vim/group/ChangeGroup.java, src/com/maddyhome/idea/vim/group/MarkGroup.java, src/com/maddyhome/idea/vim/group/RegisterGroup.java, src/com/maddyhome/idea/vim/group/copy/PutGroup.kt, src/com/maddyhome/idea/vim/group/visual/VisualMotionGroup.kt, test/org/jetbrains/plugins/ideavim/action/MarkTest.java, test/org/jetbrains/plugins/ideavim/extension/exchange/VimExchangeExtensionTest.kt
Closes [VIM-921](https://youtrack.jetbrains.com/issue/VIM-921)
Adds emulation of [vim-exchange](https://github.com/tommcdo/vim-exchange) plugin
=> VIM-921 vim-exchange plugin emulation

src/main/java/com/maddyhome/idea/vim/newapi/IjVimMessages.kt, vim-engine/src/main/kotlin/com/maddyhome/idea/vim/KeyHandler.kt, vim-engine/src/main/kotlin/com/maddyhome/idea/vim/api/VimMessages.kt, vim-engine/src/main/kotlin/com/maddyhome/idea/vim/api/stubs/VimMessagesStub.kt
This is required for vim support in Fleet.
=> Update VimMessages#updateStatusBar to accept VimEditor

src/main/java/com/maddyhome/idea/vim/group/EditorGroup.java, src/main/java/com/maddyhome/idea/vim/newapi/IjVimEditor.kt
This PR fixes an issue with #669, which would stop IdeaVim from automatically entering INSERT mode for read-only log output. This introduced the bug that it was no longer possible to type input into stdin for console-based run configurations, because a console view has a read-only editor, but allows typing.
This PR will now check if the current editor is a console view with a running process. If so, it will allow typing, even if the editor is in read-only mode. It also adds a check to see if a new editor is a console view with a running process and automatically switches to INSERT mode, to intuitively allow the user to just start typing.
=> Fix read-only stdin when running application

doc/IdeaVim Plugins.md
- Mentioned a common and very useful plugin in "Plugins" document
=> Added "Which-Key" to Plugins

src/main/java/com/maddyhome/idea/vim/listener/VimListenerManager.kt
Ensures that the editor listeners are only registered once when the editor is created. IdeaVim uses two different events to track editor creation, to try to understand how the editor is being created (new window, split, preview, etc.) and this can lead to calling the `EditorListeners.add` method twice. This would create a second `Disposable` and cause handlers to leak. This is most visible when creating the first window and then disabling IdeaVim. This window would still handle drag events like IdeaVim, even changing the caret back to block after the drag finishes.
=> Fix incorrect double registration when opening editors

src/main/java/com/maddyhome/idea/vim/extension/nerdtree/NerdTree.kt
I have used "d" to delete files and directories
=> add NERDTree action to delete files and directories

src/main/java/com/maddyhome/idea/vim/extension/nerdtree/NerdTree.kt
Similar functionality has been added in #912 and #913. [This](https://github.com/JetBrains/ideavim/pull/913#issuecomment-2182525822) was the reason given for them
=> add NERDTree action to copy, paste and rename files

src/main/java/com/maddyhome/idea/vim/handler/VimEnterHandler.kt, vim-engine/src/main/kotlin/com/maddyhome/idea/vim/command/MappingState.kt
https://youtrack.jetbrains.com/issue/VIM-3615/Escape-closes-dialog-while-waiting-for-more-keys
Please see the issue comments; I noticed strange inconsistent behavior with IdeaVIM and dialogs.
=> Fix(VIM-3615): Escape closes dialog while waiting for more keys

doc/Home.md
Currently these links give a 404
=> Fix links in doc/Home.md

src/test/java/org/jetbrains/plugins/ideavim/ex/implementation/commands/SetCommandTest.kt, src/test/java/org/jetbrains/plugins/ideavim/ex/implementation/commands/SetglobalCommandTest.kt, src/test/java/org/jetbrains/plugins/ideavim/ex/implementation/commands/SetlocalCommandTest.kt
| Before | After |
| ------ | ----- |
| ![Screenshot 2024-12-19 at 21.50.08](https://github.com/user-attachments/assets/173f70f4-93b5-44c7-b45a-58e65058e054) | ![Screenshot 2024-12-19 at 21.33.21](https://github.com/user-attachments/assets/3d048d01-9ade-41eb-9e45-8cf13ec3b9a7) |
=> Fix test failure introduced in 5e60ea7

src/test/java/org/jetbrains/plugins/ideavim/action/copy/YankMotionActionTest.kt, vim-engine/src/main/kotlin/com/maddyhome/idea/vim/yank/YankGroupBase.kt
I used the code in VimChangeGroupBase.getDeleteRangeAndType to do the check.
For an example of what this fixes, with the document:
```
${c}Hello!
```
executing "y}llp" before this change yields
```
HelHello!
lo!
```
but doing it with this change yields
```
Hello!
Hello!
````
=> Make yank motion respect exclusive-linewise

vim-engine/src/main/kotlin/com/maddyhome/idea/vim/vimscript/services/VimRcService.kt
The `XDG_CONFIG_HOME` variable should have a default value of `$HOME/.config`, but if it's set by a user, it might contain a `~`, e.g. `~/dotfiles/config`. This is probably incorrect, although this isn't stated explicitly in the docs - only that the default value should be `$HOME/.config`, which when set in a shell, will expand to a full path. 
The `~` is only recognised by shells, and expanded before being passed to a process, so an incorrect `XDG_CONFIG_PATH` variable will likely work in many cases. However, the JVM does not automatically expand `~`, so an environment variable in this form will fail when used with IdeaVim.
Since it's not obvious that the environment variable is likely incorrect, this PR will update IdeaVim to expand the `~` to the user's home directory before loading …
=> Expand `~` to home directory in XDG_CONFIG_HOME

src/main/java/com/maddyhome/idea/vim/listener/RiderSpecifics.kt
Don't insert line break on enter in insert mode for Rider, execute vim handler
=> RIDER-123506 don't insert line break on enter in insert mode for Rider
